### ISSUE TITLE
Problem download folder

### ISSUE THREAD

**Issue by rigorvzla** [gpailler/MegaApiClient#102]
@gpailler  hello man you can help me? i used this code
`client.LoginAnonymous();

                    Uri folderLink = new Uri(Settings.Default.linkMega);
                    IEnumerable<INode> nodes = client.GetNodesFromLink(folderLink);
                    Settings.Default.linkMega = String.Empty;
                    Settings.Default.Save();

                    foreach (INode node in nodes.Where(x => x.Type == NodeType.File))
                    {
                        IProgress<double> progressHandler = new Progress<double>(x => Dispatcher.Invoke(() => des.lblPorcentaje.Content = $"[{x:N0}%]"));
                        client.DownloadFileAsync(node, Settings.Default.directorioNube + "\\" + node.Name, progressHandler, cancellationToken02);
                    }
                    client.Logout();     `

But in the folder ,exist 2 file but only download 1 why,whats is wrong?

**Comment by gpailler** [comment]
DownloadFileAsync returns a Task immediately so I think you have to call the Wait method on the task. With your actual code, the Logout method will be called while the files are downloaded in the background threads and the downloads will not complete.

**Comment by gpailler** [comment]
It's not mandatory to call Logout but I think you really should await your tasks. If you have 1000 files in the folder, you will create 1000 parallel tasks with your actual code.
