### ISSUE TITLE
API response: ResourceExpired

### ISSUE THREAD

**Issue by Den4ikzxc** [gpailler/MegaApiClient#110]
Tried to login into account.
I have 2 mega accounts. First old account and second new (created recently) account. For first account code below works, for second, drop next exception on Login method:

Code:
```
MegaApiClient client = new MegaApiClient();
client.Login(Login, Password);
```
Exception:
```
 $exception | {"API response: ResourceExpired"} | CG.Web.MegaApiClient.ApiException
  | ApiResultCode | ResourceExpired | CG.Web.MegaApiClient.ApiResultCode
 InnerException | null | System.Exception
 | Message | "API response: ResourceExpired" | string
 | Source | "MegaApiClient" | string
 | StackTrace | "   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)\r\n  
 at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)\r\n   
 at CG.Web.MegaApiClient.MegaApiClient.Login(AuthInfos authInfos)\r\n   
 at CG.Web.MegaApiClient.MegaApiClient.Login(String email, String password)\r\n   
 at Storage.Mega.<LoginAcc>d__14.MoveNext() in F:\\StorageProject\\Mega.cs:line 115" | string
```

I think maybe it's problem because account is new? 

**MegaApiClient Version**: 1.6.3

**Comment by gpailler** [comment]
Seems there is a change on mega side. Official megacli application is also affected
https://github.com/meganz/MEGAcmd/issues/121

**Comment by gpailler** [comment]
Mega introduced new account type (v2). There is a prelogin call to retrieve a salt and a different login. I'll implement the required changes

Ref:
https://github.com/meganz/sdk/blob/8a8fdcc0c10cd85e020524256ea297c0daa4561b/src/megaapi_impl.cpp#L12666
https://github.com/meganz/sdk/blob/8a8fdcc0c10cd85e020524256ea297c0daa4561b/src/megaclient.cpp#L7585

**Comment by Den4ikzxc** [comment]
> Mega introduced new account type (v2). There is a prelogin call to retrieve a salt and a different login. I'll implement the required changes
> 
> Nice analysis of the changes:
> [qgustavor/mega#46 (comment)](https://github.com/qgustavor/mega/issues/46#issuecomment-437720198)
> 
> Ref:
> https://github.com/meganz/sdk/blob/8a8fdcc0c10cd85e020524256ea297c0daa4561b/src/megaapi_impl.cpp#L12666
> https://github.com/meganz/sdk/blob/8a8fdcc0c10cd85e020524256ea297c0daa4561b/src/megaclient.cpp#L7585

Thy for fast reply. Ok I will wait for changes.

**Comment by gpailler** [comment]
@Den4ikzxc Do you have time to test the latest build?
You can find it on MyGet (1.7.0-master-431)
=> https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient

**Comment by Den4ikzxc** [comment]
> @Den4ikzxc Do you have time to test the latest build?
> You can find it on MyGet (1.7.0-master-431)
> => https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient

All works Thy for fast release!

**Comment by gpailler** [comment]
Perfect. I will push a new official release on NuGet
