### ISSUE TITLE
Unable to use GetNodes since this morning

### ISSUE THREAD

**Issue by ccornen** [gpailler/MegaApiClient#121]
Hi,
Good job on this component  !!
Unfortunately, It seems that the GetNodes feature is not working anymore  (tested on two differents accounts, works only on one of them), I pooled your code and debugged the API call, actually the GetNodesRequest call returns a binary answer instead of a JSON output.
![mega_client_list_nodes](https://user-images.githubusercontent.com/24506219/54846803-f9dc6f00-4cdc-11e9-9119-d52fb4f7950f.png)

I saw you proposed a Debug program in another issue but it seems outdated, do you have another version of it ? 

Many thanks in advance for your feeback :)

**Comment by gpailler** [comment]
Hello @ccornen 
Do you still experience this issue or was it transient?
I ran the unit tests on my side and everything is working as expected.

**Comment by ccornen** [comment]
Hi @gpailler, 
Thanks for your quick feedback, seems it was a temporary mega issue, works fine this morning. Thanks for the investigation, and this connector again ;)

**Comment by gpailler** [comment]
You're welcome ;-)
