### ISSUE TITLE
MEGA folder "get link" issue

### ISSUE THREAD

**Issue by Farfie** [gpailler/MegaApiClient#13]
Oh, I didn't realize you were the maintainer here, I guess that makes sense. I figure you already know the issue then. Just having me put this here for brevity? I could copy and paste from the ShareX if you want.

**Comment by gpailler** [comment]
Hello. Please add a description of the issue you found (you can copy/paste from ShareX if you prefer)

**Comment by Farfie** [comment]
![0jsjjn 1](https://cloud.githubusercontent.com/assets/2372953/9866209/a797c338-5b2d-11e5-88cd-f7eca315af2f.png)

**Comment by gpailler** [comment]
From ShareX/ShareX#988

**Comment by Farfie** [comment]
i assume you're able to reproduce it? Would be happy to help with anything I can, though I don't know what it would be.

**Comment by gpailler** [comment]
Yes, I'm able to reproduce. I'm trying to write an UT to reproduce the problem and to fix the issue
