### ISSUE TITLE
Api Not Working

### ISSUE THREAD

**Issue by garsia0** [gpailler/MegaApiClient#133]
**Description**:
Current Vercion freez login call no error no exception

*what are you trying to do*

**Actual Behavior**:

*what happens*

**Expected Behavior**:

*what should happen* 

**Steps to Reproduce**:

1. 
2. 
3. 

**MegaApiClient Version**:

**Comment by gpailler** [comment]
Hi @garsia0 ,

Do you have a code sample to share because my free account is working perfectly.
