### ISSUE TITLE
Change default retry values to complete before user's demise

### ISSUE THREAD

**Issue by ManlyMarco** [gpailler/MegaApiClient#135]
**Description**:
The default retry settings are exponential and take an exorbitant amount of time to finish. They should be changed to something more reasonable.

https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/Options.cs#L10-L12

**Expected Behavior**:
The retry count should be around 5-10 to make the retry time manageable and allow the application to handle the issue in a timely manner.

**Steps to Reproduce**:
1. Have the mega client fail and start retrying.
2. Grow old waiting for it to finish.

**MegaApiClient Version**: v1.7.1

**Comment by gpailler** [comment]
Hi @ManlyMarco . Thanks for the report. You're right, the retry settings are probably not perfect. I will tweak them and allow custom configuration
