### ISSUE TITLE
Invalid URI

### ISSUE THREAD

**Issue by Kuhicop** [gpailler/MegaApiClient#138]
**Description**:

Invalid uri. Unable to extract Id and Key from the uri https://mega.nz/file/qngU0SLb#LKpljv7WtAT-Z0k4IuLwgby7g4OBhOFiBVzIkylD_iY

I've tested uploading the file 3-4 times to get different link but doesn't work with any link

*what are you trying to do*

Download a single file from mega link

**Actual Behavior**:

Doesn't download anything, it says the uri is invalid

*what happens*

I'm getting this error: Invalid uri. Unable to extract Id and Key from the uri https://mega.nz/file/qngU0SLb#LKpljv7WtAT-Z0k4IuLwgby7g4OBhOFiBVzIkylD_iY

**Expected Behavior**:

Downloading the file from that url

**Steps to Reproduce**:

```C#
var client = new MegaApiClient();
client.LoginAnonymous();
Uri fileLink = new Uri("https://mega.nz/file/qngU0SLb#LKpljv7WtAT-Z0k4IuLwgby7g4OBhOFiBVzIkylD_iY");
INodeInfo node = client.GetNodeFromLink(fileLink);
client.DownloadFile(fileLink, node.Name);
client.Logout();
```

**MegaApiClient Version**: 1.7.1

**Comment by AlttiRi** [comment]
[They have changed the links format.](https://github.com/meganz/webclient/commit/a43b633bb156515bb9d6d79e0a3e0cedcdadb143)
New ones:
"https://mega.nz/file/SHARE_ID#DECTYPTION_KEY"
"https://mega.nz/folder/SHARE_ID#DECTYPTION_KEY"
"https://mega.nz/folder/SHARE_ID#DECTYPTION_KEY/file/SELECTED_NODE_ID"
"https://mega.nz/folder/SHARE_ID#DECTYPTION_KEY/folder/SELECTED_NODE_ID"


The old link format for a selected file node in a folders share leads to a special page:
The link:
https://mega.nz/#F!e1ogxQ7T!ee4Q_ocD1bSLmNeg9B6kBw!P8BBzaTS
The page:
![folder_with_selected_file](https://user-images.githubusercontent.com/16310547/78289843-737f7d80-752b-11ea-968a-9cbacfcbe437.png)

**Comment by Kuhicop** [comment]
So I guess I have to wait for the API to get updated?

**Comment by AlttiRi** [comment]
You can transform the link to the old format manually. (Until the fix comes out.)
For example (your link): https://mega.nz/#!qngU0SLb!LKpljv7WtAT-Z0k4IuLwgby7g4OBhOFiBVzIkylD_iY

The old format:
"https://mega.nz/#!SHARE_ID!DECRYPTION_KEY" – for a file
"https://mega.nz/F#!SHARE_ID!DECRYPTION_KEY" – for a folder
"https://mega.nz/F#!SHARE_ID!DECRYPTION_KEY!SELECTED_NODE_ID"

**Comment by gpailler** [comment]
@Kuhicop I added support for new links format. Could you try the following MyGet package https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient/1.7.1-138-newurl-508 ?

@AlttiRi Thanks a lot for the very useful URL examples

**Comment by AlttiRi** [comment]
It works for me, tested via `git clone`.
