### ISSUE TITLE
Exception on Login(string email, string password)

### ISSUE THREAD

**Issue by alex1a** [gpailler/MegaApiClient#14]
Hi, i'm testing some code and try to make a simple mega connection. he give me a exception after Login debug line.

        private const string Username = "batatas_jor@hotmail.com";
        private const string Password = "****";

        protected MegaApiClient _client;
        private MegaApiClient.AuthInfos auth;

        /// <summary>
        /// Initializes a new instance of the <see cref="FormMega"/> class.
        /// </summary>
        public FormMega()
        {
            InitializeComponent();

            Dbg.WriteLine("Mega API Client");
            _client = new MegaApiClient();
            
            Dbg.WriteLine("Auth");
            auth = MegaApiClient.GenerateAuthInfos(Username, Password);

            Dbg.WriteLine("Login");
            _client.Login(auth);
            
            Dbg.WriteLine("Nodes");
            var nodes = _client.GetNodes();
            INode root = nodes.Single(n => n.Type == NodeType.Root);
            INode myFolder = _client.CreateFolder("AlexCommands", root);
            INode myFile = _client.Upload("test.txt", myFolder);

            Dbg.WriteLine("Open URL");
            Uri downloadUrl = _client.GetDownloadLink(myFile);
            if (downloadUrl != null) Process.Start(downloadUrl.ToString());

**Comment by alex1a** [comment]
bump

**Comment by gpailler** [comment]
I checked your snippet and it's working fine without any error on my side (I tried with your credentials before you remove them. I encourage you to change your password because it was visible during few hours).

Can you send the exception text you get?

**Comment by alex1a** [comment]
thanks, i alredy do it. i'm with a custom debugging class and can't see the exception info i don't know why. but one question, u use that code above ? i try to make that on my own and don't know if was the correct implementation.

**Comment by gpailler** [comment]
I used this part from your snippet
```
Dbg.WriteLine("Mega API Client");
        _client = new MegaApiClient();

        Dbg.WriteLine("Auth");
        auth = MegaApiClient.GenerateAuthInfos(Username, Password);

        Dbg.WriteLine("Login");
        _client.Login(auth);

        Dbg.WriteLine("Nodes");
        var nodes = _client.GetNodes();
        INode root = nodes.Single(n => n.Type == NodeType.Root);
```

I was able to retrieve root node from your account and I noticed you have more than 14.000 nodes. I didn't try to create a node because you said you had a auth exception

**Comment by alex1a** [comment]
yeah the auth exception occurs after the "auth = MegaApiClient.GenerateAuthInfos(Username, Password);" or after "_client.Login(Username, Password);"

today i will get more info about the exception and post here. thanks for support, btw is any other c# option of C# Api framework for Mega ? your seems to be the best option, u do all the raw work with c++ mega sdk ?

**Comment by gpailler** [comment]
I don't use MegaSDK code at all. It's was done by reverse engineering the traffic between mega.co.nz and the browser.

**Comment by alex1a** [comment]
This is my ouput after running the login_test().
Here are my FormMega.cs form class: http://pastebin.com/zFBTj9u8

```
15-10-2015 07:27:15 ## Mega API Client
15-10-2015 07:27:15 ## Auth
15-10-2015 07:27:16 ## Login
A first chance exception of type 'System.IO.FileNotFoundException' occurred in MegaApiClient.dll
A first chance exception of type 'System.IO.FileNotFoundException' occurred in MegaApiClient.dll
A first chance exception of type 'System.IO.FileNotFoundException' occurred in MegaApiClient.dll
15-10-2015 07:27:16 ## NO
A first chance exception of type 'System.IO.FileNotFoundException' occurred in AlexCommands.exe
A first chance exception of type 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
The program '[6624] AlexCommands.exe' has exited with code -1 (0xffffffff).
```

**Comment by gpailler** [comment]
Ok. Can you have more details about the exception FileNotFoundException (you can activate catch of these exceptions in VisualStudio)?.

Do you have the required dependency Newtonsoft.Json (if you installed using Nuget, it should be ok) ?.

**Comment by alex1a** [comment]
seems okey, i just need to update all nuget packages and work fine. sorry for delay and thanks for support ;)

**Comment by gpailler** [comment]
You're welcome
