### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by erri120** [gpailler/MegaApiClient#140]
**Description**

*what are you trying to do*
Login using an account with Two-Factor Authentication

**Actual Behavior**:
*what happens*
Error code `-26` (see #139)

**Expected Behavior**:

*what should happen* 
Option to input the TFA code.

**MegaApiClient Version**:
latest

**Comment by kiddailey** [comment]
I'd like to suggest that it would be nice to allow the creation of separate credentials for applications that share an account similarly to what GitHub (and others) do.  Or perhaps implement OAUTH.

I have an automation application that needs to access an account in the background, so I won't be able to prompt the user for 2FA each time the app needs to sign in, perform it's actions and sign out.
