### ISSUE TITLE
WinForms Implementation

### ISSUE THREAD

**Issue by mrvodka007** [gpailler/MegaApiClient#148]
Hi there, I really like this project and am currently using it to implement in a MEGA file browser, just one question: How would I go about implementing this in WinForms with a tree view. I know how to do this with local files but this is different and the example in the documentation only shows a recursive function that can only work in a command line interface.

Do you have any ideas on how to implement this in a tree view so folders are properly added to a tree view?

Thanks, mrvodka007.

**Comment by gpailler** [comment]
It's not so different from displaying local files. The method GetNodes() retrieves all the nodes as a flat list. You can use some Linq queries to filter the nodes based on the parent and build your hierarchy in a treeview.

For example, if I start from this example: https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/creating-an-explorer-style-interface-with-the-listview-and-treeview, the following code should work to build nodes for folders.
Obviously, you will have to adapt according to your needs to also display files, trash... or to implement a dynamic loading by subscribing the BeforeExpand event

```csharp
private void PopulateTreeView()
{
    IEnumerable<INode> nodes = this.client.GetNodes().ToArray();
    INode root = nodes.Single(n => n.Type == NodeType.Root);
    
    TreeNode rootNode = new TreeNode(root.Name);
    rootNode.Tag = root.Id;
    this.GetDirectories(nodes, rootNode);
    this.treeView1.Nodes.Add(rootNode);
}

private void GetDirectories(IEnumerable<INode> nodes, TreeNode nodeToAddTo)
{
    IEnumerable<INode> folders = nodes.Where(n => n.ParentId == nodeToAddTo.Tag && n.Type == NodeType.Directory);
    foreach (INode folder in folders)
    {
        TreeNode  aNode = new TreeNode(folder.Name, 0, 0);
        aNode.Tag = folder.Id;
        aNode.ImageKey = "folder";
        
        this.GetDirectories(nodes, aNode);
        nodeToAddTo.Nodes.Add(aNode);
    }
}
```

**Comment by streamen21** [comment]
Thank so much mr gpailler , it work perfect after some modification

> It's not so different from displaying local files. The method GetNodes() retrieves all the nodes as a flat list. You can use some Linq queries to filter the nodes based on the parent and build your hierarchy in a treeview.
> 
> For example, if I start from this example: https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/creating-an-explorer-style-interface-with-the-listview-and-treeview, the following code should work to build nodes for folders.
> Obviously, you will have to adapt according to your needs to also display files, trash... or to implement a dynamic loading by subscribing the BeforeExpand event
> 
> ```cs
> private void PopulateTreeView()
> {
>     IEnumerable<INode> nodes = this.client.GetNodes().ToArray();
>     INode root = nodes.Single(n => n.Type == NodeType.Root);
>     
>     TreeNode rootNode = new TreeNode(root.Name);
>     rootNode.Tag = root.Id;
>     this.GetDirectories(nodes, rootNode);
>     this.treeView1.Nodes.Add(rootNode);
> }
> 
> private void GetDirectories(IEnumerable<INode> nodes, TreeNode nodeToAddTo)
> {
>     IEnumerable<INode> folders = nodes.Where(n => n.ParentId == nodeToAddTo.Tag && n.Type == NodeType.Directory);
>     foreach (INode folder in folders)
>     {
>         TreeNode  aNode = new TreeNode(folder.Name, 0, 0);
>         aNode.Tag = folder.Id;
>         aNode.ImageKey = "folder";
>         
>         this.GetDirectories(nodes, aNode);
>         nodeToAddTo.Nodes.Add(aNode);
>     }
> }
> ```

Thank so much mr gpailler , it work perfect after some modification
