### ISSUE TITLE
Uploads fail and API reports error that secure connection is required

### ISSUE THREAD

**Issue by kiddailey** [gpailler/MegaApiClient#150]
**Description**:

Uploads do not appear to work anymore for some reason.   The code I am using was written a few months ago and at the time it did work within a WPF app.  I am now developing for iOS using Xamarin and now the API complains that a secure connection is not being used.  I have not yet retested the WPF application to see if it is also broken there as well.

**Actual Behavior**:

Upload never completes, hanging app as it attempts to repeatedly try to upload.  The following error appears repeatedly in the console:

> load failed with error Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., NSErrorFailingURLStringKey=http://gfs270n075.userstorage.mega.co.nz/ul/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/0, NSErrorFailingURLKey=http://gfs270n075.userstorage.mega.co.nz/ul/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/0, 

You can see that the URLs it is using are not https.

**Steps to Reproduce**:

I'll try to update this with additional steps later, but basically, I'm performing the following steps:

1. Creating a new MegaApiClient

```
apiClient = new MegaApiClient();
```

2. Calling the Login() method

```
sessionToken = apiClient.Login(username, password);
```

3. Getting the root node

```
rootNode = nodes.Single(x => x.Type == NodeType.Root);
```

4. Creating a folder off of the root node with CreateFolder()

```
folderNode = CreateFolder(folderName, rootNode);
```

5. Uploading a single-byte semephore file to the created folder using Upload() or UploadAsync()

```
var memoryStream = new MemoryStream(new byte[1], false);
fileNode = apiClient.Upload(memoryStream, fileName, folderNode);
```

Everything works file until the last step of uploading the file.  I am able to connect, login, and create folders without any issues.  It is only the upload that fails.

**MegaApiClient Version**: 1.8.1

**Comment by kiddailey** [comment]
Strange.   I did some stepping through the MegaApiClient.Tests.UploadStream_DifferentParent_Succeeds() test and can confirm that Mega appears to be returning a regular HTTP scheme instead of HTTPS in it's json responses.  But the upload still succeeds for some reason and the tests pass.

I added a little https check and updated the uri if it wasn't secure in the Upload method and the test still passed.  Going to see if that helps my case as well.

**Comment by gpailler** [comment]
Hi @kiddailey,

Yes, as far as I know, Mega uses regular HTTP URLs because everything is encrypted/decrypted on the client-side and it's useless to encrypt a second time for the transport.
I never used the MegaApiClient for a Xamarin/iOS app but the error looks really related to iOS. There is probably an option or a setting to allow insecure URLs.

Please keep me informed if you find a workaround and I will update the documentation.

**Comment by kiddailey** [comment]
Wow.  Thank you for that reply.  It got me on the right path to solving this by prompting me to re-read the original error, which sent me into Apple documentation world :)

Basically, the issue is that some time ago, Apple began enforcing the requirement of secure connections in iOS.  Like you said, Mega uses HTTP for file transfers, so these connections are getting blocked by ATS (App Transport Security).  

The solution turned out to be surprisingly simple.  All iOS apps have an info.plist XML file that dictates various app settings and specifics (bundle version, name, required iOS version, app icon, etc).  In that file, you can specify settings for ATS, which includes a flag to allow insecure HTTP:

```xml

<key>NSAppTransportSecurity</key>
  <dict>
    <key>NSExceptionDomains</key>
    <dict>
      <key>mega.co.nz</key>
      <dict>
        <key>NSIncludesSubdomains</key>
        <true/>
        <key>NSExceptionAllowsInsecureHTTPLoads</key>
        <true/>
      </dict>
      <key>mega.nz</key>
      <dict>
        <key>NSIncludesSubdomains</key>
        <true/>
        <key>NSExceptionAllowsInsecureHTTPLoads</key>
        <true/>
      </dict>
    </dict>
  </dict>
```

By adding this block into my iOS app's info.plist file, everything works.  Note that it works with only an exception for "mega.co.nz"  However, I added "mega.nz" for completeness since they seem to use both.  That *should* hopefully be enough info for the documentation and I can close this issue.

Thanks again!
