### ISSUE TITLE
Login does not work if password contains non ASCII-127 characters

### ISSUE THREAD

**Issue by pp111** [gpailler/MegaApiClient#158]
To test it configure a mega account with a password that contains the character ë 
It will not be possible to login

**Comment by gpailler** [comment]
Hi, Which version are you using because a similar issue #96 was fixed on 1.6.3

**Comment by G-i-o** [comment]
Had this issue with one of the following chars in my pwd. The removal of them, solved the issue. Not sure which one.

£$^*-
