### ISSUE TITLE
Library not working anymore

### ISSUE THREAD

**Issue by openbullet** [gpailler/MegaApiClient#159]
Hello, mega.nz changed their whole login system apparently and this library is not working anymore.
I would like to know if you plan on changing it to work again or if I should use a different solution, thanks.

**Comment by gpailler** [comment]
Hi @openbullet ,
I ran the whole tests suite this morning and all unit tests are green so the library should work: https://ci.appveyor.com/project/gpailler/megaapiclient/builds/36570064/tests

Could you share more details about the error you are facing?

**Comment by openbullet** [comment]
Hi again, I'm terribly sorry for opening this issue without checking thoroughly first. Turns out my test account was blocked because I accessed it through a VPN and mega sent me a reset link through email, so I was getting a ResourceAdministrativelyBlocked response and thought the endpoint was changed.

Thank you for running the test suite, and thank you for this amazing library.

**Comment by gpailler** [comment]
No worries 👌
