### ISSUE TITLE
Add Thumbnails/Previews

### ISSUE THREAD

**Issue by DidgetMidget** [gpailler/MegaApiClient#160]
**Description**:
I wanted to do like a preview for some files so i dont need to download and then show it the offical api got something for that but there is no function for this lib

*what are you trying to do*
Get the preview picture for pictures and videos

**MegaApiClient Version**:
newest 

Sry if i post this on the wrong place never done posting before and i dunno where to request features

**Comment by gpailler** [comment]
Hi @DidgetMidget 
You were correct, creating an issue is the proper way for a feature request.

It's a good idea and we should check the mega.nz API calls to find how the thumbnails are requested. I will flag this issue as a request and will take a look.

Thanks

**Comment by DidgetMidget** [comment]
Hello @gpailler 
![image](https://user-images.githubusercontent.com/54773103/103483336-dd90c000-4de6-11eb-811c-c738d42a4803.png)
I found this in their doc and there is no way to do this with the code you already provide right?
Like the data shuld be somewhere in the node i guess with "type 0" they mean like their "directory/file/root" stuff right? 

Thanks you for looking into it! ^^

**Comment by gpailler** [comment]
The library doesn't support thumbnails at all. You are right, it appears that the node has an additional property called file attribute (`fa` for short) and it's not used by MegaApiClient. The JSON data for a node looks like:
```
{
   "h":ID
   "p":PARENT
   "u":OWNER
   "t":TYPE
   "a":SERIALIZED ATTRIBUTES
   "k":SERIALIZED KEY
   "s": SIZE
   "fa":"925:0*Q37tnVMWcHI/826:1*2C5EpDqvQ8E",
   "ts":SERIALIZED CREATIONDATE
}
```
In this example, The `fa` property has 2 values and `"925:0*Q37tnVMWcHI` contains an identifier used to retrieve the thumbnail (and you can see the type 0 the doc is talking about).

I will check if we can easily retrieve this thumbnail

**Comment by DidgetMidget** [comment]
That would be nice thanks a bunch for your quick reply

**Comment by gpailler** [comment]
Hi @DidgetMidget ,

I added support for Thumbnails and Previews download. Could you take a shot?

You can download the pre-release version from MyGet: https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient

Then you can use the new method called `IMegaApiClient.DownloadFileAttribute(...)` to download the Thumbnail or Preview associated with a node (from my tests, the thumbnail and the preview are stored as jpeg).
You can also check the available file attributes on a node by accessing the property `INode.FileAttributes`

Your feedback is welcome.

Thanks!

**Comment by DidgetMidget** [comment]
Hey @gpailler 

Thank you for adding it in it works great!

But if a file dosn't contain a preview then i get a null exception but thats a problem i need to fix on my end (directly creating a bitmap out of that stream so yeah thats the problem^^)

But if i encounter any issues in the future i will report them here.
 
Keep up the good work with your api client!

**Comment by gpailler** [comment]
Thanks for the feedback!

Yes if the file attribute is not available, the returned Stream is null. Before trying to retrieve a file attribute, you can check if it exists by looking at the FileAttributes property on the node.

I will publish a new public version with this new API soon. Thanks again

**Comment by AuroraDysis** [comment]
@gpailler But it seems to be missing the ability to generate a preview when uploading images.

https://github.com/meganz/sdk/blob/master/bindings/java/nz/mega/sdk/MegaUtilsAndroid.java

https://stackoverflow.com/questions/54075745/how-to-create-thumbnail-image-in-net-core-using-the-help-of-iformfile
