### ISSUE TITLE
[BUG] Duplicate directories being created in mega

### ISSUE THREAD

**Issue by davidbuckleyni** [gpailler/MegaApiClient#161]
Folders are being duplicated even though the folder names are identical just the filename that is different mega upload is creating to independent folders UploadFileAsync inside my loop but mega should only be creating one folder as they are the same just the filename that is different?

Yes I understand am doing this 

     public async Task<IActionResult> UploadFiles([FromForm]FileManagerViewModel fileManager)
        {
            var uploads = Path.Combine(hostingEnvironment.WebRootPath, "Uploads");
            string uploadsUserId = uploads + @"\" + UserId.ToString() + @"\";

            if (!Directory.Exists(uploadsUserId))
                Directory.CreateDirectory(uploadsUserId);
            foreach (IFormFile formFile in fileManager.File)
            {
                string fullFile = uploads + @"\" + UserId.ToString() + @"\" + formFile.FileName;
                using (var stream = new FileStream(fullFile, FileMode.Create))
                {
                    await formFile.CopyToAsync(stream);
                }

                if (ModelState.IsValid)
                {

                    FileClient client = new FileClient();
                    FileInfo info = new FileInfo(formFile.FileName);
                    var remoteIpAddress = _httpContextAccessor.HttpContext.Connection.RemoteIpAddress;
                    await client.UploadFileAsync(_context, "username", "password", fullFile, info.Extension.ToLower(), UserId.ToString(), remoteIpAddress.ToString());
                }

            }
            return View("~/Views/FileManager/Index.cshtml", _context.FileManager.Where(w => w.UserId == UserId).ToList());
        }

My Upload code 

     public async Task<double> UploadFileAsync(MSFSAddonDBContext context, string UserName,string Password, string fileName,string extension,string userId,string ipAddress)

        {
            double progressValue=0.00;
            var client = new MegaApiClient();
            client.Login(UserName, Password);
            
            IEnumerable<INode> nodes = client.GetNodes();

            INode root = nodes.Single(x => x.Type == NodeType.Root);
            INode myFolder = client.CreateFolder(userId, root);
            var progress = new Progress<double>();
            progress.ProgressChanged += (s, progressValue) =>
            {
                //Update the UI (or whatever) with the progressValue 
                progressValue = Convert.ToInt32(progressValue);
            };
            if (uploadCancellationTokenSource.IsCancellationRequested)
            {
                uploadCancellationTokenSource.Dispose();
                uploadCancellationTokenSource = new CancellationTokenSource();
            }

            INode myFile =await client.UploadFileAsync(fileName, myFolder,progress, uploadCancellationTokenSource.Token);
            Uri downloadLink = client.GetDownloadLink(myFile);
            Console.WriteLine(downloadLink);
            FileManger uploadRecord= new FileManger();
            Guid.TryParse(userId, out Guid userIdValue);
            uploadRecord.UserId = userIdValue;
            uploadRecord.isZipFile = true;
            uploadRecord.OrignalFilename = fileName;
            uploadRecord.FileExtension = Path.GetExtension(fileName);
            uploadRecord.isActive = true;
            uploadRecord.IPAddressBytes = ipAddress;
            uploadRecord.isDeleted = false;
            uploadRecord.CreatedDate = DateTime.Now;
            uploadRecord.CreatedBy = UserName;
            uploadRecord.canBeDownloadedByOtherUsers = true;
            uploadRecord.DownloadLink = downloadLink.ToString();
            var upload = context.FileManager.Add(uploadRecord);
            await context.SaveChangesAsync();
            client.Logout();

            return progressValue;
        }

![image](https://user-images.githubusercontent.com/5619229/104797715-2584ef00-57b8-11eb-9a5b-52e718c52a76.png)

You will see here the second folder with the second file but in fact this should be in the above folder I think what is hapening cause their no way to check if a node exists its duplicating it.

![image](https://user-images.githubusercontent.com/5619229/104797736-46e5db00-57b8-11eb-88ba-01c7f4753fd2.png)

I am using .net 5 asp.net web mvc project hope this is just something simple

**Comment by gpailler** [comment]
Hi @davidbuckleyni 
Technically, it's possible to create multiple directories with the same name on Mega and it's what is happening in your case.

In your method `UploadFileAsync`, you should first check if the folder already exist and call `CreateFolder` only if the folder is not in the nodes list.

Something like the following should solve your issue:
```
public async Task<double> UploadFileAsync(MSFSAddonDBContext context, string UserName,string Password, string fileName,string extension,string userId,string ipAddress)
{
  [...]
  IEnumerable<INode> nodes = client.GetNodes();

  INode root = nodes.Single(x => x.Type == NodeType.Root);
  INode myFolder = nodes.SingleOrDefault(x => x.ParentId == root.Id && x.Type == NodeType.Directory && x.Name == userId) ?? client.CreateFolder(userId, root);
  [...]
}

**Comment by davidbuckleyni** [comment]
Hi Sorry what should I check against i see the where caluse in the my folder is it that the x.name = ?

**Comment by davidbuckleyni** [comment]
Thanks a million it worked who owns mega these days do u find it reliable seem a good solution for my file sharing probelm is i have to save the file locally to server and then transmit to mega.

**Comment by gpailler** [comment]
I don't know if Mega is the best solution for your file-sharing problem because it depends of the service you want to provide. But if you store files for customers/clients, it's probably not the best and most reliable solution (compared to Amazon S3 / Azure blobs...)

**Comment by davidbuckleyni** [comment]
I agree but amazon S3 is beyond my price espcially if u talk about the size of msfs add ons some can be 2gb or more in size.

**Comment by davidbuckleyni** [comment]
Is their a way in your wrapper library to get the file name in the url instead of just the download link ?

**Comment by gpailler** [comment]
You can use [`GetNodeFromLink()`](https://gpailler.github.io/MegaApiClient/api/CG.Web.MegaApiClient.MegaApiClient.html#CG_Web_MegaApiClient_MegaApiClient_GetNodeFromLink_System_Uri_) to retrieve filename from an URI. Is it what you are looking for?

(btw, could you please close this issue as it was sorted out)

**Comment by phobos04** [comment]
> 
> 
> Hi @davidbuckleyni
> Technically, it's possible to create multiple directories with the same name on Mega and it's what is happening in your case.
> 
> In your method `UploadFileAsync`, you should first check if the folder already exist and call `CreateFolder` only if the folder is not in the nodes list.
> 
> Something like the following should solve your issue:
> 
> ```
> public async Task<double> UploadFileAsync(MSFSAddonDBContext context, string UserName,string Password, string fileName,string extension,string userId,string ipAddress)
> {
>   [...]
>   IEnumerable<INode> nodes = client.GetNodes();
> 
>   INode root = nodes.Single(x => x.Type == NodeType.Root);
>   INode myFolder = nodes.SingleOrDefault(x => x.ParentId == root.Id && x.Type == NodeType.Directory && x.Name == userId) ?? client.CreateFolder(userId, root);
>   [...]
> }
> ```

Hi,

I'd like to inform you that I'm having the same issue described by the OP.
I'm already checking if the folder exists.
The strange behaviour is that if I use my Web Api with my account, I don't get the dup folders (expected behaviour).
The problem comes in when my Web Api is used with my customer's account, which contains tons of files and folders. 
In both cases I use `GetNodesFromLinkAsync(parentLink)` in order to avoid a full tree traversal.
Please, do you know whether this problem could be related with the account complexity?

Thank you so much.
