### ISSUE TITLE
"File Not Decrypted" error when uploading to existing folder via Mega link

### ISSUE THREAD

**Issue by phobos04** [gpailler/MegaApiClient#162]
**Description**:

I'm working on a .NET Core 3.1 web API that uploads files to a Mega Account.
I can successfully upload one or more files to any folder and subfolder if I read the nodes starting from the root folder of that account. As the destination account is big an filled up with a complex folders and files structure, I'm trying to figure out a way to speed up the upload process.

**Actual Behavior**:

When I try to upload a file to a folder, and I do not fully traverse the folder structure, but I get the folder node using this code:
```
var nodes = await _client.GetNodesFromLinkAsync(uri);
// NodeType.Root is used here because the debugger shows that the INode I need is the "Root" of that mega link.
INode myFolder = nodes.SingleOrDefault(w => w.Type == NodeType.Root && w.Name == folderName);
```
I can correctly get the expected node.
Then, when I upload the file with this code:
```
// file is a class that stores the file name and the file content (Stream)
foreach (var file in files)
{
  // check if file already exists 
  INode myFile = nodes.SingleOrDefault(w => w.Type == NodeType.File && w.ParentId == myFolder.Id && w.Name == file.FileName);
  // delete old version of the file
  if (myFile != null) await _client.DeleteAsync(myFile, false);

  var progress = new Progress<double>();
  progress.ProgressChanged += (s, progressValue) =>
  {
    //Update the UI (or whatever) with the progressValue 
    Console.WriteLine($"{file.FileName} Upload Progress: {progressValue}");
  };
  using (MemoryStream ms = new MemoryStream())
  {
    file.Content.Seek(0, SeekOrigin.Begin);
    file.Content.CopyTo(ms);
    var bytes = ms.ToArray();
    using MemoryStream dataStream = new MemoryStream();
    dataStream.Write(bytes, 0, bytes.Length);
    dataStream.Position = 0;

    myFile = await _client.UploadAsync(dataStream, file.FileName, myFolder, progress);
  }
  // alternative upload procedure (same results as the previous one)
  //using (MemoryStream dataStream = new MemoryStream())
  //{
  //    file.Content.Seek(0, SeekOrigin.Begin);
  //    await file.Content.CopyToAsync(dataStream);
  //    dataStream.Position = 0;

  //    myFile = await _client.UploadAsync(dataStream, file.FileName, myFolder, progress);
  //}

```
If I try to use existing folder's mega link (that I already have from previous uploads), the browser's mega client says "file not decrypted".

**Expected Behavior**:

I should be able to upload one or more files to any existing folder in the data structure without traversing all the data structure.
Those files shoud be accessible by pointing a browser to tha original folder's Mega url.

**MegaApiClient Version**: 1.8.2

**Comment by gpailler** [comment]
Hi @phobos04 ,

It's a very clever way to upload a file without having to download the whole tree and I have to admit that I never tested this scenario before.

I just created a very simple test and it appears that's working fine. The file is properly uploaded and can be opened in the browser or downloaded.

```csharp
var client = new MegaApiClient();
client.Login("[USER]", "[PASSWORD]");

var nodes = await client.GetNodesFromLinkAsync(new Uri("https://mega.nz/folder/[ID]#[KEY]"));
var root = nodes.Single(x => x.Type == NodeType.Root);
var createdNode = await client.UploadFileAsync(@"[PATH]\SampleFile.jpg", root);
await client.DownloadFileAsync(createdNode, @"[PATH]\SampleFile-dl.jpg");
```

Could you try this sample with your folder's mega link and a simple file?

**Comment by phobos04** [comment]
Hi @gpailler 
I'll try to adapt your example, but I cannot try it as it is.
I have no access to local file paths. I use `UploadAsync` with streams I get from HTTP Post requests. Does `UploadAsync` works somewhat differently than `UploadFileAsync`?
Then, My API is for file upload only.  After successful file uploads my users receive an email with the folder's mega link. The link is generated after the first upload to the folder (new folder), or re-used for subsequent uploads. My users use that link in a broswer to access the uploaded files.
The strange behavior is that while the files uploaded with a full tree traversal (no matter how many nesting levels) are correctly decrypted and available, the files uploaded (with the same code I've posted in the foreach statement) are not correctly decrypted.

Thank you so much.

**Comment by phobos04** [comment]
I can confirm that the strange behaviour is still there.

The only thing I could change was rewriting this:  
`INode myFolder = nodes.SingleOrDefault(w => w.Type == NodeType.Root && w.Name == folderName);`
into  
`INode myFolder = nodes.Single(x => x.Type == NodeType.Root);`

But still no luck.
Unuckily, traversing all the tree all the times is extremely time consuming, because the Mega account I'll be uploading to in production is crowded and full of folders and small files.
The error I'm reporting is happening on my test account, which is simple and periodically cleaned.

**Comment by gpailler** [comment]
`UploadFileAsync` calls `UploadAsync` internally so it should not make any difference.

With your latest comment, I was able to understand what was the issue and I can reproduce it. The file is marked as "not decrypted" when you use the public link without being logged in to Mega (or with different credentials). When using the credentials used to upload the file, you can access the file.

The issue is that when you use the method `GetNodesFromLinkAsync`, the `INode.SharedKey` property is not populated and the file is uploaded as a "private" file. The file is visible but you cannot decrypt it. Actually, the only way to generate `INode` instances with the `SharedKey` populated is to call the `GetNodes()` method. 
It appears that's a Mega limitation because even Mega web client doesn't allow to upload a file in a shared folder (when opening the folder's mega link directly).

So I think the best (and only) solution is to call `GetNodes()` once and cache the nodes you are interested in (and update the cache from time to time if needed).

**Comment by phobos04** [comment]
Thank you for the details.
I think we could close this Issue, as it is not related to the `MegaApiClient` per-se.
