### ISSUE TITLE
Folder upload

### ISSUE THREAD

**Issue by VladislavAntonyuk** [gpailler/MegaApiClient#169]
**Description**:

I would like to upload folders

Add new API:
Task UploadFolderAsync(string localPath, string folderName, INode parentNode);
void UploadFolder(string localPath, string folderName, INode parentNode)

**MegaApiClient Version**:
1.9

**Comment by VladislavAntonyuk** [comment]
Still actual

**Comment by gpailler** [comment]
MegaApiClient doesn't support folder upload/download as it involves handling conflicts (when part of the files already exists at the destination). But it's quite easy for the integrators to implement folder upload/download and handle conflicts on their side.
