### ISSUE TITLE
Is there some kind of event that trigger when new file was uploaded?

### ISSUE THREAD

**Issue by frost7412359** [gpailler/MegaApiClient#170]
Is there some kind of event that trigger when new file was uploaded?

**Comment by gpailler** [comment]
No there is no event raised at the end of an operation.

- `IMegaApiClient.Upload(...)` methods are synchronous so you can raise your own event after the upload
- `IMegaApiClient.UploadAsync(...)` methods are asynchronous so you can have a continuation task to raise your own event after the upload
- You can also pass a `IProgress<double>` object to track the progression
