### ISSUE TITLE
[Request] Security risk when using Login()

### ISSUE THREAD

**Issue by JPPlaysGamer** [gpailler/MegaApiClient#176]
**Description**:

I'm new to the API and I have a problem if I'm going to post on some project repository site for future reference (like GitHub) to have in code snippet the credentials like Email and user password which could be bad for the developer.

**Actual Behavior**:

Assuming you make a program that logs into your account to do manipulations in the cloud. If you create and publish it WITH your email and password, it can be a danger to your account.
`Client.Login("Your email", "Password")` Find someone it causes harm if he uses it.

**Expected Behavior**:

When calling the MegaApiClient.Login() function, is it possible to login without being able to "leak" personal data?

**Steps to Reproduce**:

1. Install API.
2. Instantiate the class.
3. Call Login() without use personal credentials. 

**MegaApiClient Version**: 1.9.0.0

**Comment by gpailler** [comment]
The library requires credentials information at some point to authenticate on the Mega.nz service and to decrypt the master key. I don't see any way to avoid that. 
I think it's the developer responsibility to not leak any secret in the repository/source code or in the published binaries.
