### ISSUE TITLE
Confusing methods naming

### ISSUE THREAD

**Issue by Bardin08** [gpailler/MegaApiClient#177]
**Description**:
The IMegaApiClient provides two methods: GetNodeFromLinkAsync and GetNodesFromLinkAsync. As a user, I expect both methods to return an instance(-s) of INode or INodeInfo.
```csharp
Task<INodeInfo> GetNodeFromLinkAsync(Uri uri);
Task<IEnumerable<INode>> GetNodesFromLinkAsync(Uri uri);
```

**Actual Behavior**:
Now, GetNodeFromLinkAsync returns an instance of INodeInfo when GetNodesFromLinkAsync returns an IEnumerable<INode>.

**Expected Behavior**:
Both methods should return the same type, or one of them should be renamed.

**MegaApiClient Version**: 1.9.0 (NuGet)

**Comment by gpailler** [comment]
Hi thanks for your report. I will check to make `GetNodeFromLinkAsync ` and `GetNodesFromLinkAsync ` consistent

**Comment by gpailler** [comment]
1.10.0 released
