### ISSUE TITLE
All calls to megaclient API hanging

### ISSUE THREAD

**Issue by itzlokeshjayaraj** [gpailler/MegaApiClient#178]
**Description**: I logged in using "sessionid" and "masterkey".

*what are you trying to do*
Trying to fetch account info,  get nodes, download link, etc.

**Actual Behavior**:
The methods GetAccountInformation(...) , GetNodes(...), etc,., is hanging for ever.
*what happens*
Any call to these methods are hanging..

**Expected Behavior**:
The methods GetAccountInformation(...) , GetNodes(...) should return appropriate objects on success.
*what should happen* 
These methods were working fine previously, but all of sudden not working now

**Steps to Reproduce**:

1. Login using "sessionid" and "masterkey".
2. Call GetAccountInformation(...) or GetNodes(...) or any other method
3.  No response but instead hanging
4.  Sometimes i am getting these errors but not consistent
"   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)\r\n   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)\r\n   at CG.Web.MegaApiClient.MegaApiClient.GetAccountInformation()\r\n   at 

OR

"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at CG.Web.MegaApiClient.WebClient.PostRequest(Uri url, Stream dataStream, String contentType)\r\n   at CG.Web.MegaApiClient.WebClient.PostRequestJson(Uri url, String jsonData)\r\n   at CG.Web.MegaApiClient.MegaApiClient.RequestCore[TResponse](RequestBase request, Byte[] key)\r\n   at CG.Web.MegaApiClient.MegaApiClient.Request[TResponse](RequestBase request, Byte[] key)\r\n   at CG.Web.MegaApiClient.MegaApiClient.GetAccountInformation()\r\n  

**MegaApiClient Version**: 1,7 to 1.9

**Comment by gpailler** [comment]
I tried to reproduce your issue but everything is working properly. Maybe it's a network issue on your side. Did you check with another account and/or another PC?

**Comment by itzlokeshjayaraj** [comment]
Hi,
The issue is not consistent. It is working for some accounts(same or different PC) whereas not so for some others. 
Also For the same account, but with different session id's, one is working and other not so. 
The accounts which are working too takes a lot of time to respond.(~ 2mins). 
Sometimes Manual proxy setup is "enabled" to use proxy server and issue appears at that time, but that too not consistent. So, it is difficult for me to correlate the exact reason. 
Any clues to sort out the issue is appreciated...
Thanks in advance...

**Comment by gpailler** [comment]
You can subscribe the event IMegaApiClient.ApiRequestFailed to get some details about the API failures.
From my experience, Mega has some rate-limiting policy that could lead to the behavior you are describing. 
Do you use free or pro accounts?

**Comment by itzlokeshjayaraj** [comment]
Hi,
Can you share a code snippet of how to subscribe this event IMegaApiClient.ApiRequestFailed.?
FYI, Mine is a free account and Can you share some doc/articles to know more on this rate-limiting policy?

**Comment by gpailler** [comment]
For example:
```csharp
var client = new MegaApiClient();
client.ApiRequestFailed += OnApiRequestFailed;

[...]

private void OnApiRequestFailed(object _, ApiRequestFailedEventArgs e)
{
  Debug.WriteLine($"ApiRequestFailed: {e.ApiResult}, {e.ApiUrl}, {e.AttemptNum}, {e.RetryDelay}, {e.ResponseJson}, {e.Exception} {e.Exception?.Message}");
}
```

About the rate limit, it's mentioned on the Mega doc => https://mega.nz/doc (API_ERATELIMIT) but there is not much details.
Anyway, the snippet I posted above could help to understand the root issue.

**Comment by itzlokeshjayaraj** [comment]
Hi, Implemented the subscription as per your code snippet. The methods GetAccountInformation(...) , GetNodes(...), etc,., is hanging for ever or giving responses after ~ 2 mins. But control is never coming to the OnApiRequestFailed(....) method 
FYI, sometimes Manual proxy setup is turned on while hanging, but it is not consistent.

**Comment by gpailler** [comment]
Well, then there is no throttling if OnApiRequestFailed is never called.
You can use Fiddler or implement your own IWebClient to investigate the connections and try to understand why it's taking so long.

**Comment by gpailler** [comment]
@itzlokeshjayaraj Could you try the solution posted on https://github.com/gpailler/MegaApiClient/issues/181#issuecomment-937378384. It looks it's exactly the issue you are facing.

**Comment by gpailler** [comment]
Documentation is updated with a note about new TLS requirement

⚠️ TLS 1.2 support should be configured explicitely when using .NET Framework <= 4.5 or all the API calls to Mega will hang.
- For .NET Framework 4.5, add ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
- For .NET Framework 4, add ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072; (.NET 4.5 should be installed on the machine).

https://github.com/gpailler/MegaApiClient/blob/d85f00cbcc2e1b409ce504358db9f0f93c4e139e/docs/index.md?plain=1#L31-L33

**Comment by mastercho** [comment]
using .NET Core 5 with your lib and supports TLS 1.2 and issue still exists and is exactly as  itzlokeshjayaraj describes hungs on sone and works for some other. I just test with normal HTTP req to mega API and its working fine but with normal HTTP is flagged as suspicious activity and would lock your account. Was good library until this issue is come out, maybe they change something you have to look deeper into this issue.


> Hi, The issue is not consistent. It is working for some accounts(same or different PC) whereas not so for some others. Also For the same account, but with different session id's, one is working and other not so. The accounts which are working too takes a lot of time to respond.(~ 2mins). Sometimes Manual proxy setup is "enabled" to use proxy server and issue appears at that time, but that too not consistent. So, it is difficult for me to correlate the exact reason. Any clues to sort out the issue is appreciated... Thanks in advance...

**Comment by Bluekey21** [comment]
Public Function Sube_Archivo_Mega(ByVal Usuario As String, ByVal Contrasena As String, ByVal CarpetaNube As String, ByVal RutaArchivo As String) As Boolean
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        Try

            Dim Cliente As New MegaApiClient()

            Cliente.Login(correo@gmail.com, xxxxx)

            Dim Nodos = Cliente.GetNodes()
            Dim Root As INode
            Dim Carpeta As INode

            If CarpetaNube <> "" Then
                Dim ExisteCarpeta As Boolean = Cliente.GetNodes().Any(Function(n) n.Name = CarpetaNube)

                If ExisteCarpeta = True Then
                    Carpeta = Nodos.[Single](Function(n) n.Name = CarpetaNube)
                Else
                    Root = Nodos.[Single](Function(n) n.Type = NodeType.Root)

                    Carpeta = Cliente.CreateFolder(CarpetaNube, Root)
                End If
            Else
                Carpeta = Nodos.[Single](Function(n) n.Type = NodeType.Root)
            End If

            Dim Archivo As INode = Cliente.UploadFile(RutaArchivo, Carpeta)

            Dim DownloadUrl As Uri = Cliente.GetDownloadLink(Archivo)

            UrlDescarga = DownloadUrl.ToString

            Cliente.Logout()
-----------------------------------

And it still hangs, Where as same credentials works well to login in browser.

**Comment by sabihismail** [comment]
I'm having the same issue, I've only been able to trace it to the `private TResponse RequestCore<TResponse>(RequestBase request, byte[] key)` function never being exited on some occasions, I'll update if I can get more specific.

**Comment by Tonnilson** [comment]
> I'm having the same issue, I've only been able to trace it to the `private TResponse RequestCore<TResponse>(RequestBase request, byte[] key)` function never returning and infinitely stalling on some occasions, I'll update if I can get more specific.
> 
> Edit: Narrowed it to stalling in the function call to `PostRequest(Uri url, Stream dataStream, string contentType)` within `PostRequestJson` within `RequestCore<TResponse>(RequestBase request, byte[] key)`. Is it possible that there is a deadlock here for these async `.Result` calls?
> 
> Edit 2: So this appears to be because `this.httpClient.SendAsync` in `PostRequest(Uri url, Stream dataStream, string contentType)` never exits for some reason since the `httpClient` timeout is set to infinite. Not entirely sure if this is a good solution, I set `responseTimeout = 20000` in the constructor and changed `PostRequestJson` to
> 
> ```
> public string PostRequestJson(Uri url, string jsonData)
> {
>     try
>     {
>         using (MemoryStream jsonStream = new MemoryStream(jsonData.ToBytes()))
>         {
>             using (var responseStream = this.PostRequest(url, jsonStream, "application/json"))
>             {
>                 return this.StreamToString(responseStream);
>             }
>         }
>     }
>     catch
>     {
>         return null;
>     }
> }
> ```
> 
> so that it throws an exception after 20 seconds rather than stalling forever. This causes for it to retry the same request (there's retry logic in the calling function) and I seem to not be blocked anymore. Hope this helps!

The timeout being set to infinite by default is most likely the issue people are experiencing. With that in mind you can set the timeout to your desired timeout and catch it and handle it from there on your own.

```csharp
MegaApiClient client = new MegaApiClient(new WebClient(20000));

                try
                {
                    client.LoginAnonymous();
                } catch
                {
                    //handle it here
                }
```
Your solution works fine to make it auto retry but these things are use case and user preference. Having the option to set a property for auto-retrying and changing the DefaultResponseTimeout from infinite to something reasonable should be an appropriate fix / implementation.

**Comment by gpailler** [comment]
For those who can reproduce the API hanging issue, could you try the following NuGet package to confirm that an exception is thrown about the lack of Tls12 support?
https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient/1.10.0-pullrequest0186-0012

Thanks

**Comment by gpailler** [comment]
1.10.0 released
