### ISSUE TITLE
wrong result url from mega upload

### ISSUE THREAD

**Issue by Dadude123** [gpailler/MegaApiClient#18]
hi im using sharex and i was told to report the bug here because it seems to be a problem inside the api

upload a file to mega with credentials set.
it won't copy the correct url to your clipboard, when you try to download it in the browser, the progressbar will go to 100% and then it will say "decryption error".

but when i go to the file in mega after sharex has uploaded it and copy the full link manually it works.
and the link i get when copying the link also looks completely different than the one sharex got.

**Comment by gpailler** [comment]
I reproduce this issue. I will investigate. Thanks for the report
