### ISSUE TITLE
Reading a File

### ISSUE THREAD

**Issue by IsaacJuracich** [gpailler/MegaApiClient#183]
Do you have to download a file, or can you read a file through the api?

**Comment by gpailler** [comment]
If you use the `Stream Download(...)` method, you can read a file content without saving it on the disk 
Does it work for you?

**Comment by IsaacJuracich** [comment]
I'll test soon, thank you.

**Comment by Galvans77** [comment]
hi @gpailler 

i´m very interested on reading the file content without saving on the disk, what do you mean with "Stream Download(...)"? could you expand that?

thank you in advance.
