### ISSUE TITLE
Issue with Uploading

### ISSUE THREAD

**Issue by IsaacJuracich** [gpailler/MegaApiClient#184]
When I upload a file I can physically interact with it on mega.nz, but If I recheck the folder with the files inside of it. It's not there.

**Comment by IsaacJuracich** [comment]
I believe I found the source of the issue I believe. I uploaded the file without a folder and reupdated and checked and it's there. So, I believe its something with folders.

**Comment by gpailler** [comment]
Hello @IsaacJuracich 
Your description is a bit unclear. Could you post more details about the issue?

Thanks

**Comment by IsaacJuracich** [comment]
Yeah, So, when I download a file off of the cloud and edit the file and re upload it. When i log into mega.nz I can open the file and change contents, but when the bot tries to check all current files in that folder that file doesn't pop up anymore. Unless I download it and re upload it physically myself. After some testing, I found if I don't upload it to a folder and into the main folder it's there and I don't have to physically reupload myself.

**Comment by gpailler** [comment]
Your issue is quite strange. Could you provide a small code snippet so I can reproduce it?

**Comment by IsaacJuracich** [comment]
Uri folderLink = new Uri("https://mega.nz/folder/URMSkDqD#MNTup1y2PcM0XD6hht0XGQ");
            IEnumerable<INode> nodes = client.GetNodesFromLink(folderLink);
            INode node = nodes.Single(x => x.Type == NodeType.Root);
            client.UploadFile("test.txt", node);
            
^ - To upload the file

            Uri folderLink = new Uri("https://mega.nz/folder/URMSkDqD#MNTup1y2PcM0XD6hht0XGQ");
            IEnumerable<INode> nodes = client.GetNodesFromLink(folderLink);
            foreach (INode node in nodes.Where(x => x.Type == NodeType.File)) {
                Console.WriteLine(node.Name);
            }

^ - To get all of the files in the folder

**Comment by gpailler** [comment]
Thanks for the details.
Actually, modifying a share is not supported by Mega.nz and you receive an AccessDenied error if you try to do it (when calling Delete, Move, CreateFolder... for example).
I don't know why the Mega.nz API doesn't report the same error when you try to upload a file to a share but I will add a check to throw a proper error.

**Comment by IsaacJuracich** [comment]
Appreciate it.

**Comment by gpailler** [comment]
1.10.0 released
