### ISSUE TITLE
How to download a file on the web, I am using ASP.NET 4.5 (MVC)

### ISSUE THREAD

**Issue by mateoagudelo** [gpailler/MegaApiClient#185]
**Description**: I have a problem when downloading files, the site keeps loading.

*what are you trying to do* 
I am trying to download mega files from a website made with ASP.NET 4.5

**Actual Behavior**: 
When I access the URL to download the file, it keeps loading and does not return any error.

*what happens*
The file is not downloaded, the files I am trying to download are public.

**Expected Behavior**:
File download

**Steps to Reproduce**:

1. I access https://localhost:44328/Home/Download
2. Site stays in a loading loop

**My Code**: 

`
using CG.Web.MegaApiClient;
using System.Threading.Tasks;

        public void Download()
        {
            var client = new MegaApiClient();
            client.LoginAnonymous();

            Uri fileLink = new Uri("https://mega.nz/file/TctykRzL#p5xkGEj..........etc");
            INodeInfo node = client.GetNodeFromLink(fileLink);

            //Console.WriteLine($"Downloading {node.Name}");
            client.DownloadFile(fileLink, node.Name);

            client.Logout();
        }

`

**MegaApiClient Version**: 1.9.0

**Comment by gpailler** [comment]
Hello,

Could you ensure you have the required values in `ServicePointManager.SecurityProtocol` ?
=> https://github.com/gpailler/MegaApiClient/issues/181#issuecomment-937378384

**Comment by mateoagudelo** [comment]
### Thanks for you reply!

Now I have the following problem:

`<html>
<body>


[UnauthorizedAccessException: Access to the path 'C:\Windows\SysWOW64\inetsrv\File.rar' is denied.]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +12602111
--


</body>
</html>`

**Comment by gpailler** [comment]
Well you have to specify a writeable directory for your file in the `DownloadFile` method
