### ISSUE TITLE
Handle HttpClient lifetime MegaApiClient ctor

### ISSUE THREAD

**Issue by igorquintaes** [gpailler/MegaApiClient#188]
**Description**:

A [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) is sightly different from a common objects in .NET. It inherits from HttpMessageInvoker, a disposable class that opens and maintains HTTP request connections. furthermore, and unfortunately, to call a `httpClient.Dispose()` does not dispose properly all unmanaged resources as it should do, because sockets are related to executing process due how OS works.

Here is an [example](https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) about what i wrote. Now, let's imagine a solid application that uses MegaApiClient as an Scoped lifetime, managed by .NET service provider (or any other lib that to IoC, like SimpleInjector or even Ninject). Every time that a MegaApiClient is instanced, a new HttpClient is created. After some time, application is going to crash due sockets quantity opened.

Now, let's look [MegaApiClient Line 42](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/MegaApiClient.cs#L42). In its parameterless ctor (and with Options param too), it creates a new WebClient instance. Now inside [WebClient_HttpClient Line 20](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L20) it calls his internal ctor providing a null value to messageHandler, creating a new HttpClient in [line 28](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L28). To understand what is happening, we need to open and read lib source code to find a alternative approach. This strange kind of problem mainly appears in hmg/productive environment due high load, where errors thrown aren't expected and has large impacts :(

**Actual Behavior**:
Creating multiples MegaApiClient can crash application.

**Expected Behavior**:
An stable application and be able to inject MegaApiClient as scoped/transient without troubles in all ctors. Due issue #172 it is even unable to be a singleton instance - furthermore is important allow transient or scoped instances due some implementation needs, as multiple accounts management, server or client-side.

**How we can bypass for now**:
So if you need transient, scoped or even manually multiple MegaApiClient instances for now, we have to create an own WebClient instance and pass it in MegaApiClient ctor [here](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/MegaApiClient.cs#L57).

**How to fix that**:
In a simple approach: don't create a new WebClient inside ctors in MegaApiClient class. Just create a private static instance and share it in ctors. I had a fast-look into WebClient class and it does not hold state, except than [line 34 - BufferSize](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L34) that don't look to be troublesome. If you still want to assure his right use, would be nice to set it as private and allow to pass a value in ctor too.

Also, if you want to create MegaApiClient instances with a service injection extension, i would recommend to read [IHttpClientFactory Microsoft's documentation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests). It has a very clear explanation about how HttpClient works more deeply and how to handle issues while injecting it in multiples scopes or calls.

**Steps to Reproduce**:

The bellow code does the trick with HttpClient. You need to create and open a request. Maybe you can find a way to easily reproduce using MegaApiClient lib code.

```cs
var parallelOptions = new ParallelOptions { MaxDegreeOfParallelism = Environment.ProcessorCount * 2 };
Parallel.For(0, 100000, parallelOptions, _ =>
{
    using var client = new HttpClient();
    client.GetAsync("http://google.com").GetAwaiter().GetResult();
});
```

**MegaApiClient Version**: latest

**Comment by gpailler** [comment]
Hello @igorquintaes 
Thanks for your very detailed report and explanation!

I was well aware of the HttpClient limitation when creating multiple instances and to be honest, I was far to imagine when I started this project, almost 10 years ago, that MegaApiClient would be used in high load environments.
Anyway, I will follow your proposal and will improve WebClient_HttpClient to share a single HttpClient instance between all WebClient_HttpClient instances. 
And, as you have noticed, you can provide your own IWebClient implementation if you are using DI with >= .NET Core 2.1 and want to use a IHttpClientFactory.

**Comment by igorquintaes** [comment]
I hit that issue when doing a stress test in my application, maybe it never occurs in my production environment but i imagined that a fixing could help someone. It is nice to see your project growing like that!

**Comment by gpailler** [comment]
1.10.0 released
