### ISSUE TITLE
Thread freeze for delayed requests 

### ISSUE THREAD

**Issue by igorquintaes** [gpailler/MegaApiClient#189]
**Description**:

If we create a MegaApiClient and take sometime to call it, app freezes in [WebClient_HttpClient Line 76](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L76), not throwing any error neither unlocking it. Maybe [Line 16](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L16), where a timeout is set as infinite, is masking the real problem.

**Actual Behavior**:

Freezing, without throwing errors neither skipping request. 

**Expected Behavior**:

Throw an error to application handle scenario, due login expired or other issue. Or just execute it if still ok. 

**Reproducing**:

```cs
var client = new MegaApiClient();
client.Login("XXXXX", "XXXXX"); // valid login here
Thread.Sleep(1000 * 60 * 5); // 5 min
client.GetNodes().Single(x => x.Type == NodeType.Root);
```

Call Stack image:
![image](https://user-images.githubusercontent.com/10831729/140620959-c551677c-6fdc-41cc-a71f-50a62f4acbe6.png)

**MegaApiClient Version**: latest (master branch too)

**Comment by gpailler** [comment]
Interesting report. I will take a look on it. Thanks

**Comment by gpailler** [comment]
I was able to reproduce the issue. The culprit is the `ConnectionClose = false` in [WebClient_HttpClient.cs#L48](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L48).
I'm updating `WebClient_HttpClient.cs` in the scope of #188 and this issue should be fixed as a side effect.

Thanks again

**Comment by igorquintaes** [comment]
Thanks for your fast response and fixing!

**Comment by gpailler** [comment]
1.10.0 released
