### ISSUE TITLE
GetNodeFromLink throws a NullReferenceException

### ISSUE THREAD

**Issue by SensouShin** [gpailler/MegaApiClient#192]
**Description**:
I'm trying to download a public file as you described with in your example, but when it's calling GetNodeFromLink,  it throws a NullReferenceException. It cames from the Node constructor where its trying to parse file attributes. The cause of this issue is in the DownloadResponse where SerializedFileAttributes is null. When i'm trying to bypass this issue then the DownloadFile throws a ResourceNotFoundExeption. Target Framework: .NET Core 3.0

*what are you trying to do*
I'm trying to download a puplic file from mega with your example code. 

**Actual Behavior**:
Throws a Null Reference Exception

**Expected Behavior**:
Return a Node for the file

**Steps to Reproduce**:

```
var megaClient = new MegaApiClient();
megaClient.LoginAnonymous();

Uri fileLink = new Uri("https://mega.nz/file/qngU0SLb#LKpljv7WtAT-Z0k4IuLwgby7g4OBhOFiBVzIkylD_iY");
INode fileNode = megaClient.GetNodeFromLink(fileLink);

string outputFileName= Environment.CurrentDirectory + "\\downloads\\" + fileNode.Name + ".rar";
Directory.CreateDirectory(outputFileName);

megaClient.DownloadFile(fileNode, outputFileName);
```
**Stack Trace**
>	MegaApiClient.dll!CG.Web.MegaApiClient.Node.DeserializeFileAttributes(string serializedFileAttributes) Line 219	C#
 	MegaApiClient.dll!CG.Web.MegaApiClient.Node.Node(string id, CG.Web.MegaApiClient.Serialization.DownloadUrlResponse downloadResponse, byte[] key) Line 36	C#
 	MegaApiClient.dll!CG.Web.MegaApiClient.MegaApiClient.GetNodeFromLink(System.Uri uri) Line 674	C#
 	OsuMapDownloader.dll!OsuMapDownloader.Program.Main(string[] args) Line 103	C#

**MegaApiClient Version**:
1.10

**Comment by gpailler** [comment]
Thanks for the feedback 👍 . Issue will be fixed in upcoming 1.10.1
