### ISSUE TITLE
GetNodes does not get any info about nodes

### ISSUE THREAD

**Issue by Porkechebure** [gpailler/MegaApiClient#198]
**Description**:
Trying to get some simple links with anonymous login
Used the base sample here
https://gpailler.github.io/MegaApiClient/articles/samples.html

**Actual Behavior**:

Links are grabben but most informations are null
![image](https://user-images.githubusercontent.com/3466040/143782548-d4285e96-fe74-4b09-88f8-ad00f4ef83ed.png)

I tried both with Anonymous login and with credentials login. Same result.

**Expected Behavior**:

Getting all the links with all informations correctly.
Moreover, it can't recognize correctly the nodes, so DisplayNodesRecursive does not work.

**Steps to Reproduce**:

1. New console project (tried .NET 5, .NET 4.8, .NET 4.7.1, doesn't change anything)
2. put the code from your samples
3. Post any mega link

**MegaApiClient Version**:
1.10.2

**Comment by gpailler** [comment]
Could you post a sample to reproduce the issue?
On your screenshot, the result is expected. The nodes Root/Trash/Inbox are special nodes and expose only a couple of properties.

**Comment by Babai-42** [comment]
To avoid creating a separate question, I'll ask here. How can I display the entire list of files on a public link. C# code example if possible.

**Comment by gpailler** [comment]
Hello @Babai-42 

You can take a look on this [sample](https://gpailler.github.io/MegaApiClient/articles/samples.html#download-folder-content-from-a-mega-link) .
