### ISSUE TITLE
Accessing an uploaded file publicly

### ISSUE THREAD

**Issue by magedadel** [gpailler/MegaApiClient#199]
**Description**:
Thank you for this great API. This is most likely not an issue. 

*what are you trying to do*
I'm able to upload the file to the cloud, however, I want to get a link to it so I can render the image within the app in an HTML image tag.
Is this possible? 

Thank you.
**MegaApiClient Version**:

**Comment by gpailler** [comment]
You can call the method `IMegaApiClient.GetDownloadLink(INode)` to retrieve an URL to download the file you have just uploaded but I don't think that you can retrieve a direct URL to the file/image (you always have a landing page to start a download on Mega)
