### ISSUE TITLE
GetNodes() for just the nodes with a certain parent?

### ISSUE THREAD

**Issue by PhilippCTest** [gpailler/MegaApiClient#203]
I would like to present a file browser to my users. Therefore, I'd like to call `GetNodes()`, but only receive the results for the root folder or any particalar folder into which the user browses. Is this possible?

I understand that I can filter the response locally for certain parents, but as https://gpailler.github.io/MegaApiClient/articles/samples.html states that `GetNodes()` can be slow, that doesn't sound like a great implementation.

**Comment by PhilippC** [comment]
I posted this with the wrong Github account, sorry :-)

**Comment by gpailler** [comment]
Well, you will have to call GetNodes() and keep a cache of the nodes locally. There is no way to retrieve only a part of the tree, as far as I know.

**Comment by PhilippC** [comment]
ok, thanks
