### ISSUE TITLE
Uri doesn't support MEGAdrop folder link.

### ISSUE THREAD

**Issue by Cr33zz** [gpailler/MegaApiClient#204]
**Description**:

I'm trying to upload file to MEGA using MEGAdrop folder link.

**Actual Behavior**:

I'm getting exception when trying to GetNodeFromLink and creating Uri instance for that. I replaced my link id with X-es.
```
System.ArgumentException: 'Invalid uri. Unable to extract Id and Key from the uri https://mega.nz/megadrop/XXXXXXXXXX'
```

**Steps to Reproduce**:

This is the code I'm using
```
var megaClient = new CG.Web.MegaApiClient.MegaApiClient();
megaClient.LoginAnonymous();
var folderOnMega = megaClient.GetNodeFromLink(new Uri(@"https://mega.nz/megadrop/XXXXXXXXXX"));
megaClient.UploadFile(filePathOnComputer, folderOnMega);
megaClient.Logout();

```
**MegaApiClient Version**:

1.10.2 (nuget)

**Comment by gpailler** [comment]
This method works only for MEGAlink (https://mega.nz/folder/XXXXXX). 
MEGAdrop is not supported by MegaApiClient (but PR are welcome ;-) )

**Comment by Cr33zz** [comment]
Too bad I have no idea about how Mega works. Is it something you consider adding at some point?
