### ISSUE TITLE
Difficulties in login when many clients/many connections

### ISSUE THREAD

**Issue by DumahBrazorf** [gpailler/MegaApiClient#205]
Hi,
I'm having issues with a specific mega account that is used by several clients for backups. 
MegaApiClient the most of the times simply fails to login reporting error "Unable to cast object of type 'System.Int64' to type  'Newtonsoft.Json.Linq.JArray'" after a minute or two. I emailed mega and received this answer:
```
- About the access attempts through API:

Please note that API logins attempts could be considered as third party tool login attempts.

We are now limiting MEGA accounts session creations if they are starting too many.

Every invocation of your third party tool creates a fresh session, with all the overhead of validating your password etc.

This slows down its operation unnecessarily and accumulates sessions up to a point where it reaches our - extremely generous - limit of concurrently active sessions.

At that point, as you have experienced, our API rejects further login attempts.

In order to solve this issue, you will need to enable session persistence in your third party tool. If you don't know how, please contact its creator.
```
It seems legit. My program every few hours checks for presence of a backup file i want to upload, upload it and then remove the oldest file to save space. It does that in 3 different functions so basically it logins 3 times. It worked well like this until a week ago.
So the code (vb.net) was like:
```
Dim client = New MegaApiClient()
client.Login(TxtUser.Text, TxtPass.Text)
<dostuff>
client.Logout()
```
I had a look in the documentation and found that i can save and reuse the token session so I created a global variable 
Dim sessiontoken As MegaApiClient.LogonSessionToken
and changed the code in the functions like this:
```
Dim client = New MegaApiClient()
If Not IsNothing(sessiontoken) Then
    client.Login(sessiontoken)
Else
    sessiontoken = client.Login(TxtUser.Text, TxtPass.Text)
End If
<removed client.Logout()>
```

So my question is: Is it correct? Is it enough? 
Thanks for your work.

**Comment by DumahBrazorf** [comment]
If I save the session token without logout can i use it hours/days later?

**Comment by gpailler** [comment]
Yes, the approach by saving and reusing a token will work to enforce the throttling introduced by MEGA.

I don't know exactly how long a session is valid. You should try/catch the Login call when using a session and use a regular Login if an ApiException is thrown with an ApiResultCode.BadSessionId.
