### ISSUE TITLE
How to use with proxy ?

### ISSUE THREAD

**Issue by nocofet226** [gpailler/MegaApiClient#206]
Hello, how can I use a proxy with this library.If this is not possible, which class should be edited to add proxy support.Thanks for the answer

**Comment by gpailler** [comment]
Hi,

This topic was discussed already:
- If you are using .NET 4 (WebRequest) => https://github.com/gpailler/MegaApiClient/issues/78
- If you are using .NET 4.5 or higher (HttpClient) => https://github.com/gpailler/MegaApiClient/issues/107

**Comment by nocofet226** [comment]
Thanks for the help, but I have already solved the problem by redefining the interface.
