### ISSUE TITLE
Retrieving file name

### ISSUE THREAD

**Issue by serialtasted** [gpailler/MegaApiClient#21]
How do i retrieve the file name, without having to login. I want the file name of the file that I'm trying to download.

I've tried to use FileStream, but no luck.

**Comment by gpailler** [comment]
Currently, you cannot retrieve the filename using only the download link. It's probably a new feature to add.

**Comment by theTwist84** [comment]
Hi @gpailler just wanted to know if you've made any progress with getting the file name.

**Comment by gpailler** [comment]
It's possible to retrieve the filename (and all node attributes) only with the link. I need to have some free time to implement the new method. It's still planned for next release but no ETA for now

**Comment by gpailler** [comment]
Released on 1.2.0
