### ISSUE TITLE
Add UserAgent string

### ISSUE THREAD

**Issue by DumahBrazorf** [gpailler/MegaApiClient#210]
Hi,
it's just sad to see a list of clients "unknow" in the session history.
Can you add the userAgent variable?
Thanks.

**Comment by gpailler** [comment]
Hello,

The userAgent variable is sent and can be even customized by using a custom [WebClient](https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/WebClient_HttpClient.cs#L24) when creating a MegaApiClient instance.

The userAgent is actually displayed in the session history in a tooltip but is probably not recognized as an "official" Mega client, hence the 'Unknown' label
![tTmxkrF1Zi](https://user-images.githubusercontent.com/3621529/189509451-5bab880b-eeb4-45ac-861f-85faaaf57b07.png)

**Comment by DumahBrazorf** [comment]
Thanks for the reply.
I got it, that's unfortunate how it's showed in the list but in a certain way still usable.
