### ISSUE TITLE
Get Shared Links

### ISSUE THREAD

**Issue by dhabierre** [gpailler/MegaApiClient#214]
Is it possible to get file shared links using MegaApiClient?

I have a folder with +25000 files.
The `client.GetNodes()` takes too much time.

My idea is to get all nodes once, retrieve their shared links and store them in database.
But I can't found any property on I/Node object.

Is it possible?
Thanks 👍

**Comment by gpailler** [comment]
Hello, 
You can probably cache the INodes in your database directly instead of storing the links.
But if you want to retrieve a Download URL for a INode, you can use the method IMegaApiClient.GetDownloadLink(INode node)

**Comment by dhabierre** [comment]
Thanks!
