### ISSUE TITLE
IO Exception

### ISSUE THREAD

**Issue by serialtasted** [gpailler/MegaApiClient#22]
I'm getting this error: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in MegaApiClient.dll when trying to login anonymously. https://github.com/serialtasted/arma3Launcher/blob/v1.3/Workers/Downloader.cs (Line 293)

**Comment by gpailler** [comment]
It's probably a duplicate of #14. If you use the zip file from this repo, you should add a reference to Newtonsoft.Json (you can show details of FileNotFoundException to confirm this assembly is missing)

If you're using Nuget package, it should work.

**Comment by serialtasted** [comment]
I'm using nuget from visual studio. I did the same in a new project and it worked fine. With the same code. I'll compare both projects in terms of references.

**Comment by serialtasted** [comment]
You were right, somehow that reference disappeared from the project.
