### ISSUE TITLE
Retrieve upload progress

### ISSUE THREAD

**Issue by Croug** [gpailler/MegaApiClient#23]
Do you have any way built in to get the upload progress of a file?

**Comment by Croug** [comment]
Okay well I came up with a sort of hack to determine the upload progress. Pretty much I uploaded a filestream to the file instead of the file itself and ran that in a separate thread, and then just constantly compared the stream position to the size of the file for progress.

**Comment by gpailler** [comment]
It's not planned to add async methods in the code for now but I wrote a FAQ entry in the wiki about [async transfers](../wiki/Retrieve-progression-of-an-upload-or-download)

**Comment by Croug** [comment]
Okay , I might submit a pull request with some async methods.

**Comment by gpailler** [comment]
I'm glad if you submit a PR

**Comment by gpailler** [comment]
Pull request to integrate + UT #26

**Comment by gpailler** [comment]
Released on 1.2.0
