### ISSUE TITLE
What is the difference between `Task.Delay(retryDelay).Wait()` and `Thread.Sleep(retryDelay)`

### ISSUE THREAD

**Issue by lgeissbauer-btig** [gpailler/MegaApiClient#238]
https://github.com/gpailler/MegaApiClient/blob/768516c5666ec064d70ba4129de23749680de057/MegaApiClient/MegaApiClient.cs#L1157#L1166

Thank you :)

**Comment by gpailler** [comment]
Well `Task.Delay(retryDelay).Wait();` is more efficient because it doesn't block the other async operations that could occur on the same thread.

**Comment by lgeissbauer-btig** [comment]
Where can I read more and why is that? Is `Thread.Sleep` just a `Spin` or does it yield to another task?

**Comment by gpailler** [comment]
I'm not sure exactly where you can find deep technical information about the differences. But I think it's not directly related to this project 😇
