### ISSUE TITLE
Large file upload

### ISSUE THREAD

**Issue by vfedoniuk** [gpailler/MegaApiClient#27]
I have a problem with uploading 488 Mb  file. 
The program simply stuck while getting request stream in method PostRequest. Smaller file (413Mb) is uploading without problems.  Do anyone have encountered this issue? On the mega dev page there is written that chunked upload is also supported. Do someone know proper way of doing this?

**Comment by gpailler** [comment]
Chunked upload is not implemented in MegaApiClient. It could be a nice feature to implement.

**Comment by zeeshan47** [comment]
please help me in code for downloading the file from specific folder .

**Comment by vfedoniuk** [comment]
hi, what problem do you have?

**Comment by gpailler** [comment]
I think @zeeshan47 comment on this issue is not relevant here. He created a separate issue #30

**Comment by gaberad** [comment]
FYI, I'm getting the same issue with larger files not uploading. Not sure exactly, but its somewhere in the 400mb's range and larger.

**Comment by vfedoniuk** [comment]
i slightly changed source code to upload file in chunks and big file upload
works now.

**Comment by gpailler** [comment]
Nice! Can you  propose à pull request on develop branch?

**Comment by gaberad** [comment]
Yeah, or could you post the relavent code? I was going to take a look at chunked upload, but if you've already figured out I'll wait for your solution.

**Comment by gpailler** [comment]
I added a chunked upload implementation.
If you have time, can you test this release by using following nuget package: https://ci.appveyor.com/api/buildjobs/x4d9i6bp6nl4knih/artifacts/MegaApiClient.1.2.1.nupkg 

To use this package, you can follow this article on [SO](http://stackoverflow.com/questions/10240029/how-to-install-a-nuget-package-nupkg-file-locally) or extract the dll from the nupkg directly (it's a zip container)

**Comment by gaberad** [comment]
Tried it on some 400mb-900mb files and they all uploaded correctly for me.

**Comment by gpailler** [comment]
Thanks for your feedback. I will improve the code and will publish chunked upload for 1.2.2

**Comment by gpailler** [comment]
Released on 1.2.2
