### ISSUE TITLE
Trailing garbage in DecryptAttributes

### ISSUE THREAD

**Issue by drake7707** [gpailler/MegaApiClient#28]
I encountered multiple errors in json.net with my mega account when trying to get all the nodes. It kept complaining about trailing text after the json in the Crypto.DecryptAttributes method.

There were random characters after the last '}', probably due to the AES padding.

I've fixed the issue by substringing until the first \0 character, which is probably always used as string termination character:

```
var json = decryptedAttributes.ToUTF8String().Substring(4);
json = json.Substring(0, json.IndexOf('\0'));

return JsonConvert.DeserializeObject<Attributes>(json);
```

**Comment by gpailler** [comment]
Released on 1.2.0
