### ISSUE TITLE
Public access to MegaApiClient.authInfos

### ISSUE THREAD

**Issue by viciousviper** [gpailler/MegaApiClient#29]
Please provide public access to the field `MegaApiClient.authInfos`.

I'd like to retrieve the authInfos to store them externally and reload them at the start of an application to resume/renew the session without the user having to actively login.
Presently I have to resort to Reflection for retrieving the data from `MegaApiClient.authInfos`.

Regards
vv

**Comment by gpailler** [comment]
You can call the static method `MegaApiClient.GenerateAuthInfos(string email, string password)` to create a AuthInfos instance and serialize it. Then you can deserialize it later and login using `Login(AuthInfos authInfos)`.

**Comment by viciousviper** [comment]
Works nicely - thank you very much for pointing this out to me.
Funny that I overlooked it in the first place.
