### ISSUE TITLE
help me in downloading the file

### ISSUE THREAD

**Issue by zeeshan47** [gpailler/MegaApiClient#30]
please help me in code for downloading the file from specific folder .

in .net 4.0

**Comment by gpailler** [comment]
Hello @zeeshan47 

Can you be more specific? What problem do you face? Can you share your code?

You want download a file stored on your Mega account or using a download link?

**Comment by zeeshan47** [comment]
i want to download the file from my mega account 
 for example abc.zip fir from folder named update
i am trying this i dont know how to make nodes and get download link 

 MegaApiClient client = new MegaApiClient();

            client.Login("xxxx@gmail.com", "*****");
            var nodes = client.GetNodes();

           
            INode myFolder = client.CreateFolder("update", nodes);
            client.DownloadFile(myFolder , "abc.zip");
            MessageBox.Show("All done"); .

**Comment by gpailler** [comment]
If the file already exist on you mega account, you just have to do something like

```csharp
MegaApiClient client = new MegaApiClient();
client.Login("xxxx@gmail.com", "*****");

var nodes = client.GetNodes(); // Retrieve all folders and files
INode root = nodes.Single(n => n.Type == NodeType.Root); // Retrieve root node
INode myFolder = client.GetNodes(root).Single(n => n.Name == "update") // Retrieve update node
INode myFile = client.GetNodes(myFolder).Single(n => n.Name == "abc.zip") // Retrieve file node

client.DownloadFile(myFile, "localfile_abc.zip");
```

**Comment by zeeshan47** [comment]
Thanks alot it worked ...
