### ISSUE TITLE
compiling error in ProgressionStream.cs

### ISSUE THREAD

**Issue by zeeshan47** [gpailler/MegaApiClient#31]
![error](https://cloud.githubusercontent.com/assets/8332149/13534290/36d403fe-e256-11e5-99a0-3d80b2701685.jpg)

**Comment by gpailler** [comment]
What are you trying to do? You copied all library files in your application? In this case, you need to compile with .net 4.5 target because ProgressionStream.cs requires this version.

Why don't use the nuget package?

**Comment by zeeshan47** [comment]
yes i am using .net 4.5 .
i want to make downloader with progress bar so i added all the cs files and compiled the the project only the error is in this cs

**Comment by zeeshan47** [comment]
![image](https://cloud.githubusercontent.com/assets/8332149/13546853/b7a0815c-e2dc-11e5-91b9-b7020825c345.png)

**Comment by zeeshan47** [comment]
thanks it worked with nuget package ... can you tell how can i get the progress of any file 
beign downloaded from meaga .

**Comment by zeeshan47** [comment]
how to use this function 

Task DownloadFileAsync(INode node, string outputFile, IProgress<double> progress);

in this scenerio
/////////////////////////////////////////////
 MegaApiClient client = new MegaApiClient();
  client.Login("xxxxx@gmail.com", "*******");
 var nodes = client.GetNodes(); // Retrieve all folders and files
 INode root = nodes.Single(n => n.Type == NodeType.Root); // Retrieve root node
 INode myFolder = client.GetNodes(root).Single(n => n.Name == "Upload"); // Retrieve update node
 INode myFile = client.GetNodes(myFolder).Single(n => n.Name == "abc.txt"); // Retrieve file node

 client.DownloadFile(myFile, "abc.txt");

**Comment by gpailler** [comment]
Well in a really simple scenario, you can do something like:

```csharp
  [...]
  Progress<double> progress = new Progress<double>(this.ProgressChanged);
  this.Client.DownloadFileAsync(myFile, "abc.txt", progress);
}

private void ProgressChanged(double value)
{
  Console.Writeline(value);
}
```

But you probably have to read documentation about Tasks usages for a real case scenario (and it's not really in the scope of MegaApiClient issues ;-) )

**Comment by zeeshan47** [comment]
Thanks for your help .

**Comment by zeeshan47** [comment]
but the progress suudenly reaches at 100% when file is downloaded while fille is downloading it does not report progress ?

**Comment by gpailler** [comment]
The methods DownloadFileAsync works properly

With this code:
```csharp
class Program
{
    static void Main(string[] args)
    {
      MegaApiClient client = new MegaApiClient();
      client.Login("user", "pass");
      var nodes = client.GetNodes();
      INode root = nodes.Single(n => n.Type == NodeType.Root);
      INode myFolder = client.GetNodes(root).Single(n => n.Name == "Folder");
      INode myFile = client.GetNodes(myFolder).Single(n => n.Name == "File.jpg");

      Progress<double> progress = new Progress<double>(ProgressChanged);
      Console.WriteLine("Start download");
      client.DownloadFileAsync(myFile, "abc.txt", progress).Wait();
      Console.WriteLine("Done");
      Console.ReadLine();
    }

    private static void ProgressChanged(double value)
    {
      Console.WriteLine(value);
    }
}
````

the output is

```
Start download
10,9588831662733
21,9177663325466
32,8766494988199
43,8355326650932
54,7944158313665
65,7532989976398
76,7121821639131
87,6710653301864
98,6299484964597
100
Done
```

There is probably something wrong in you code
