### ISSUE TITLE
Thanks buddy with your help i created OTA updater for my clients

### ISSUE THREAD

**Issue by zeeshan47** [gpailler/MegaApiClient#32]
![1](https://cloud.githubusercontent.com/assets/8332149/13554964/d20e0c58-e3d6-11e5-914a-2e99d6e5f151.jpg)
![2](https://cloud.githubusercontent.com/assets/8332149/13554965/d212d288-e3d6-11e5-9b39-271c00508fbd.jpg)
![3](https://cloud.githubusercontent.com/assets/8332149/13554966/d217c770-e3d6-11e5-8639-2bd916bac507.jpg)
![4](https://cloud.githubusercontent.com/assets/8332149/13554967/d21d50d2-e3d6-11e5-8666-6e1f210dffa1.jpg)
![5](https://cloud.githubusercontent.com/assets/8332149/13554968/d221cef0-e3d6-11e5-9726-6d054874e2ad.jpg)
![6](https://cloud.githubusercontent.com/assets/8332149/13554969/d227913c-e3d6-11e5-9676-1487ffc51dad.jpg)

**Comment by gpailler** [comment]
You're welcome ;-)
