### ISSUE TITLE
Bug on serializing name of folder inside other folder

### ISSUE THREAD

**Issue by silvermcd123** [gpailler/MegaApiClient#33]
First of all, thank you for this awesome library!!!

Its not possible to get the name of a folder inside a root folder on mega (i can read the root folder name just fine)

I'm using net framework 4.5 on visual studio 2015.

Example:
```
  MegaApiClient client = new MegaApiClient();
  client.Login("email", "pw");
  List<INode> nodes = client.GetNodes().ToList();
```

http://s16.postimg.org/k7qkadrc5/bugfolder.png

**Comment by gpailler** [comment]
Hello @silvermcd123.

Can you downgrade to the previous Library version (v1.1.3) and tell me if the folder name is read properly? I applied bugfix #28 on 1.2.0 and maybe this fix introduced a regression.

Thanks

**Comment by silvermcd123** [comment]
Yes, with the version v1.1.3 i'm able to read the folders correctly

**Comment by gpailler** [comment]
Ok thanks for the test. I will fix it on next release

**Comment by gpailler** [comment]
Hello @silvermcd123.

To test the bugfix, can you:
- download the package MegaApiClient.1.2.1.nupkg from https://ci.appveyor.com/project/gpailler/megaapiclient/build/artifacts 
- launch VisualStudio and open package manager console
- execute `Install-Package MegaApiClient -Source C:\PathToTheDownloadedPackage\`

Your folder name should be displayed properly

**Comment by gaberad** [comment]
I was having this same problem, the bugfix fixed it.

**Comment by gpailler** [comment]
Ok thanks for the feedback. I will release 1.2.1 asap

**Comment by silvermcd123** [comment]
It doesnt have any artifacts on the link. but if @gaberad  can confirm its fixed, then please launch a release :)))

**Comment by gpailler** [comment]
1.2.1 released
