### ISSUE TITLE
Error downloading stream

### ISSUE THREAD

**Issue by silvermcd123** [gpailler/MegaApiClient#36]
em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   em CG.Web.MegaApiClient.MegaApiClient.SaveStream(Stream stream, String outputFile)
   em CG.Web.MegaApiClient.MegaApiClient.<>c__DisplayClass54_0.<DownloadFileAsync>b__0()
   em System.Threading.Tasks.Task.InnerInvoke()

**Comment by gpailler** [comment]
It's the typical exception you receive when the destination file already exists. If you take a look on the exception message, you should have something like `The file 'myfile.myext' already exists.`

Can you confirm?

**Comment by silvermcd123** [comment]
hum, maybe you're right, is there anyway to replace the file?

**Comment by gpailler** [comment]
Currently there is nothing in MegaApiClient to overwrite a file (on purpose for safety reason). 
In any case, you should try/catch this kind of call because even MegaApiClient was able to overwrite a file, there is lot of possible exception (the file is locked, a race condition, the drive is absent...)

**Comment by silvermcd123** [comment]
Yes you're right... what i was talking about an overload to the function DownloadFileAsync that allows to replace the files

**Comment by gpailler** [comment]
@silvermcd123 I understood your request about overloaded method. If you want, you can submit a PR with the changes and I'll be glad to integrate it but as I said, even with this new overloaded method, you still need to try/catch the Download method because other kind of exceptions can be raised
