### ISSUE TITLE
Create folder if not exists

### ISSUE THREAD

**Issue by mrjohnr** [gpailler/MegaApiClient#37]
Hi,I try your sample code to upload a file ,it does but a new Upload folder is created every time the code runs,this is my VB code (.net 3.5):

```
 Dim client As New MegaApiClient
        client.Login("mylogin@mymail.com", "mypass")
        Dim nodes = client.GetNodes()
        Dim root As INode = nodes.[Single](Function(n) n.Type = NodeType.Root)
        Dim myFolder As INode = client.CreateFolder("Upload", root)
        Dim myFile As INode = client.UploadFile("c:\test.zip", myFolder)
        Dim downloadUrl As Uri = client.GetDownloadLink(myFile)
        client.Logout()
```

thanks!

**Comment by gpailler** [comment]
Well Mega API allows to create nodes with same name. We can change CreateFolder method to  throw if we try to create a folder with a name that already exist but it's a shame to introduce this kind of limitation.
I think it's client side responsibility to get the folder node or create it if it doesn't exist.

Another solution is to add a method GetOrCreateFolder but if there is already 2 folders with the same name, the method is unable to choose and will throw.

What do you think?

**Comment by mrjohnr** [comment]
Hi! I think it is very ambiguous to have 2 or more folders/files with the same name GetOrCreateFolder  will be fine for me but not for others
You can give me some steps to implement that:create folder if it not exists or else to select the folder 

another question : do I need to distribute Newtonsoft.Json.dll ?


thanks!

**Comment by gpailler** [comment]
I don't know VB but something like that should work:
```
Dim myFolder As INode = client.nodes.[FirstOrDefault](Function(n) n.Type = NodeType.Folder And n.Name = "Upload")
If myFolder = Nothing then
    myFolder = client.CreateFolder("Upload", root)
End If
```

About Newtonsoft.Json.dll, you must distribute it with MegaApiClient

**Comment by mrjohnr** [comment]
good,it works some little corrections:
`Dim myFolder As INode = nodes.[FirstOrDefault](Function(n) n.Type = NodeType.Directory And n.Name = "upload")
        If myFolder Is Nothing Then
            myFolder = client.CreateFolder("upload", root)
        End If`

thanks!

**Comment by gpailler** [comment]
Ok my skill in VB is not so good ;-)

**Comment by shadow-dev** [comment]
Any solution for C# on this?

**Comment by gpailler** [comment]
To create a folder on root if it doesn't exist:
```
var nodes = client.GetNodes(); // Retrieve all folders and files
var root = nodes.Single(n => n.Type == NodeType.Root); // Retrieve root node

// Search a folder with "folder" name under root
var myFolder = client.GetNodes(root).FirstOrDefault(n => n.Type == NodeType.Folder && n.Name == "folder");

// Create the "folder" if not found
if (myFolder == null)
{
  myFolder = client.CreateFolder("folder", root);
}
```

**Comment by shadow-dev** [comment]
Thank you very much!

**Comment by rigorvzla** [comment]
wow man is magnific , thanks

**Comment by samuel0l0y** [comment]
I think you should make it a Boolean parameter to the CreateFolder() function.

**Comment by gpailler** [comment]
I prefer to avoid having this kind of flag because I don't want to have to download all the nodes for this check in the CreateFolder() method. MegaApiClient is "stateless" in the sense it doesn't keep a cache of the nodes and cannot make any assumption about the existing nodes structure.
I think it's the library consumer task to refresh/maintain the nodes cache and decide based on its content if a folder needs to be created or not.

 (I try to keep the library as close as possible of the real API and don't want to make extra 
- In 99.99% of the time, you don't want to  I try to keep the library close to the mega API as 
The API allows to create folders with the same name because the real identifier is an id but it doesn't make much sense I think.
Havi
