### ISSUE TITLE
Upload progress for .NET 3.5

### ISSUE THREAD

**Issue by mrjohnr** [gpailler/MegaApiClient#38]
Hi!
It is possible to have upload progress with NET 3.5,I need this
I've seen there is a feature but not for 3.5

thanks!

**Comment by gpailler** [comment]
For .net3.5, you can follow this [wiki article](../wiki/Retrieve-progression-of-an-upload-or-download)

**Comment by mrjohnr** [comment]
Hi,thanks for your answer,I can't fix 2 errors on this line:

 Using stream = New ProgressionStream(New FileStream(filepath), PrintProgression)


Error	BC30516	Overload resolution failed because no accessible 'New' accepts this number of arguments.	
Error	BC30455	Argument not specified for parameter 'progression' of 'Private Sub 
PrintProgression(progression As Double)


thanks!

**Comment by mrjohnr** [comment]
solved the error this way:
` Using stream = New ProgressionStream(New FileStream(filepath, FileMode.Open), AddressOf PrintProgression)`

but upload time now is >100 times slower,with this sample code 
` Dim myFile As INode = client.UploadFile(myfilepath, myFolder)`
it takes 4 seconds with now after 30 secods progress is 5.5 ...

**Comment by gpailler** [comment]
You probably update your UI too often. A progression event is sent for each chunk of 8KB so it's a lot of events ;-). You can reduce number of UI updates by updating your UI only once per progression percent for example

**Comment by mrjohnr** [comment]
that was,thanks!
