### ISSUE TITLE
[Feature Request] Account storage quota info

### ISSUE THREAD

**Issue by viciousviper** [gpailler/MegaApiClient#39]
Could you possibly expose an API method to determine the storage quota info for the currently used MEGA account as displayed in the web interface below the menu command *settings/overview* or the *whoami* MEGA API command?
I'd be especially interested in finding out the values for total storage capacity and currently used Cloud Drive capacity - or remaining capacity, whatever is easier.

**Comment by gpailler** [comment]
Released on 1.2.2

**Comment by viciousviper** [comment]
Works perfectly.
Thanks very much for your quick response.
