### ISSUE TITLE
[Feature Request] Seekable Download Stream

### ISSUE THREAD

**Issue by Kimi-Arthur** [gpailler/MegaApiClient#40]
Hi,

Very helpful Mega API implementation!

One possible addition to this is to make the download stream seekable.
Since the download url can be used with "Range" header, it's possible to make the download stream seekable.

I've done something similar for another storage service, without builtin encyption / decryption though.
Here is what I did to make the stream seekable:

https://github.com/Kimi-Arthur/Pimix/blob/master/src/Pimix.Cloud.BaiduCloud/BaiduCloudStorageClient.cs#L384-L385

https://github.com/Kimi-Arthur/Pimix/blob/master/src/Pimix.Cloud.BaiduCloud/SeekableDownloadStream.cs

**Comment by gpailler** [comment]
Can be an interesting feature but I didn't find any info about the Range header in https://mega.nz/#doc.
You're sure this header exists for Mega.nz?

**Comment by Kimi-Arthur** [comment]
Yes. It's there.
You can try it by first printing the response for the download url retrieval part and then use it with tools like postman to add a header like "Range: bytes:0-128" and view the response size.

**Comment by gpailler** [comment]
Ok thanks for the confirmation.
It can be a cool feature to add but I don't see real use case (when do you want to retrieve only part of a file? maybe for a movie?)

**Comment by Kimi-Arthur** [comment]
That may be one possible usage.
Another important use case is like this:
You download a file, but interrupted, you want to continue where you left because you want to save some time. (maybe discard part of the end before continuing)
Then seekable stream comes in quite handy.

**Comment by gpailler** [comment]
Merged in #75
