### ISSUE TITLE
[Feature Request] Make upload chunk size configurable.

### ISSUE THREAD

**Issue by Kimi-Arthur** [gpailler/MegaApiClient#41]
Currently the upload chunk is fixed as 128KB for first 8 chunks and 1MB for all following chunks. (I don't get the logic here either)

https://github.com/gpailler/MegaApiClient/blob/30347e1250b1a1afa63854df425b8ed3cb2a08a9/MegaApiClient/MegaAesCtrStream.cs#L282-L292

I think it will be great if people can configure the way the chunk sizes are determined. People may want to upload by chunks of 32MB or more since small chunks may increase the effect of the HTTP / API overhead.

Thanks!

**Comment by gpailler** [comment]
Chunks size you saw in MegaAesCtrStream are mandatory for Mega.nz. A checksum is created and verified for each chunk. You can find details in sections 12.2 and 12.10 on https://mega.nz/#doc

When you upload to Mega.nz you must upload chunk by chunk. Currently, I follow the chunks calculated in the stream but we can also send multiple chunks at once (according the doc 12.12).

I'm not really convinced about the overhead (but I have a poor upload 😄 ) but feel free to tweak the [upload](https://github.com/gpailler/MegaApiClient/blob/30347e1250b1a1afa63854df425b8ed3cb2a08a9/MegaApiClient/MegaApiClient.cs#L593) method an propose a PR

**Comment by Kimi-Arthur** [comment]
Here is what I found as you pointed out:

> To simplify server-side processing, partial uploads can only start and end on a chunk boundary.

But that should mean you can actually skip some boundaries if I understand it correctly.

I can try it out sometime if you don't get the time.

Thanks for the information!

**Comment by gpailler** [comment]
Yes instead uploading chunk by chunk we can upload 2 chunks by 2 chunks or send any number of chunks at once... The only requirement is to upload whole chunks. 

On [MegaApiClient.Upload](https://github.com/gpailler/MegaApiClient/blob/30347e1250b1a1afa63854df425b8ed3cb2a08a9/MegaApiClient/MegaApiClient.cs#L593), I upload data chunk by chunk but you can try to tweak the code to create a MemoryStream containing multiple chunks and uploading it.
