### ISSUE TITLE
Downloading File[SOLVED]

### ISSUE THREAD

**Issue by woramon** [gpailler/MegaApiClient#42]
I want to download the file in the user's path. Example:
`string Path = folder\somefolder\somefolder2\somefile.file` This can be change and I want to download "somefile.file" help me please.

**Comment by gpailler** [comment]
I don't really understand your question. folder\somefolder\somefolder2\somefile.file is the storage path on your mega account?

**Comment by woramon** [comment]
Yes it is but its In a different path for each user's mega account. Example:
user1 file path for download:`string Path = folder\somefolder\somefolder2\somefile.file`
user2 file path for download: `string Path = folder2\somefolder2\somefile2.file` 
user3 ....

**Comment by gpailler** [comment]
You can use the following to get your file:
```
var nodes = megaApiClientInstance.GetNodes();
var root = nodes.Single(n.Type == NodeType.Root);
var level1 = megaApiClientInstance.GetNodes(root).Single(n => n.Type == NodeType.Folder && n.Name == "folder");
var level2 = megaApiClientInstance.GetNodes(level1).Single(n => n.Type == NodeType.Folder && n.Name == "somefolder");
var level3 = megaApiClientInstance.GetNodes(level2).Single(n => n.Type == NodeType.Folder && n.Name == "somefolder2");
var file = megaApiClientInstance.GetNode(level3).Single(n => n.Type == NodeType.File && n.Name == "somefile.file");
```

If your file has an unique name, another way is to request it directly
```
var file = megaApiClientInstance.GetNodes().Single(n => n.Type == NodeType.File && n.Name == "somefile.file");
```
(it works because mega.nz stores all files/folders in a flat list and `GetNodes()` methods returns all nodes.)

**Comment by gpailler** [comment]
😄 Feel free to contribute and add samples...
