### ISSUE TITLE
The ApiClient is missing "rename" fuctionality

### ISSUE THREAD

**Issue by Kimi-Arthur** [gpailler/MegaApiClient#45]
**Description**:

With the Move method, the client can move file from one place to another, but the file name cannot be changed.

**Actual Behavior**:

No such method provided.

**Expected Behavior**:

Provide a rename method or the move method accepts a third parameter as new file name.

**Other notes**

When we do rename on the website, it actually calls an API with action id being "a".

The API is also available as SetAttr method. See [here](https://github.com/meganz/sdk/blob/master/src/commands.cpp#L751).

**Comment by gpailler** [comment]
You're right. The rename method is missing
I plan to add at least a Rename method on next release

**Comment by Kimi-Arthur** [comment]
Thanks! That's great to hear!
