### ISSUE TITLE
Acces Denied error when I call GetDownloadLink(INode)

### ISSUE THREAD

**Issue by ArchonDeveloper** [gpailler/MegaApiClient#46]
Hello I have above issue. What can be the issue?

**Comment by mOrfiUs** [comment]
I use GetDoenloadLink in this routine and works fine.
dll .Net 4.0 (32 and 64 because i hve two diff servers)

`
List<WaitHandle> events = new List<WaitHandle>();
            Parallel.ForEach(lToUp, new ParallelOptions { MaxDegreeOfParallelism = LoA.iSimultaneousUp }, f =>
            {
                MegaApiClient cMegaForEach = new MegaApiClient();
                try
                {
                    cMegaForEach.Login(LoA.userMega, LoA.passMega);
                    Stopwatch dur = new Stopwatch();
                    dur.Start();

                    string l = string.Empty;
                    using (var streamUp = new FileStream(f, FileMode.Open, FileAccess.Read))
                        l = cMegaForEach.GetDownloadLink(cMegaForEach.Upload(streamUp, f, LoA.nodeBkUpFolder)).ToString();

                    if (!string.IsNullOrEmpty(l))
                        if (LoA.bCheckSHA1 == 1)
                        {
                            ManualResetEvent mre = new ManualResetEvent(false);
                            ThreadPool.QueueUserWorkItem (
                                delegate(object o)
                                {
                                    checkSha1File(LoA, l);
                                    ((ManualResetEvent)o).Set();
                                }, mre);
                            events.Add(mre);
                        }
                    string sR = new util().sizeReadable(new FileInfo(f).Length / dur.Elapsed.TotalSeconds) + "/s";
                    dur.Stop();
                    lOk.Add(new string[4] { DateTime.Now.ToString("HH:mm:ss"), f, sR, l });
                }
                catch (Exception ex)
                {
                    lErr.Add(new string[3] { DateTime.Now.ToString("HH:mm:ss"), f, ex.Message });
                }
            });
`

**Comment by gpailler** [comment]
@ArchonDeveloper Could you attach a minimal code to reproduce your issue?

**Comment by ArchonDeveloper** [comment]
Actually my code is simple:
var foundNode = _currentNodes.FirstOrDefault(item => item.Name == imageGuid);
var p = _currentClient.GetDownloadLink(foundNode);

But foundNode is a folder and not a file. Could it be the issue?
Also I found that mega sends next message [{"a":"l","n":"PgEwUYhJ","i":"eAZpKfOp2x"}]. And message from your code is without "i" argument like [{"a":"l","n":"PgEwUYhJ"}]. When I'm trying to send request(via Fiddler in composer) without "i", I'm getting the same code error (-11).

Thanks for trying help me.

**Comment by gpailler** [comment]
Thanks for the details. You're probably right, GetDownloadLink method should work only with files. I will add support for folders

**Comment by ArchonDeveloper** [comment]
Thanks for that. Will wait on new release ;)
