### ISSUE TITLE
GetAccountInformations won't work

### ISSUE THREAD

**Issue by Pilzinsel64** [gpailler/MegaApiClient#47]
I'm writing a programm that must check out the current space of the mega account.
I'm using MegaClientApi Version 1.2.2 (the newest one).

To get the accountinfos i'm doing this:
Dim accinfo As IAccountInformation = (Await ServerMgr.server_levels(i).GetAccountInformationAsync)

Then i try to get the this values:
Dim maxserverspace As Long = accinfo.TotalQuota
Dim curserverspace As Long = accinfo.UsedQuota

At both i get this error:
https://gyazo.com/cd53c1f60abad6a28af113f2490040e4

Few weeks ago it worked correctly.
Hope this will be fixed very soon ...

Thank you! :)

**Comment by gpailler** [comment]
Hello @Pilzinsel64. 

Do you have valid values in accinfo variable?
According the screenshot, you're trying to convert a long value for TotalQuota to an integer. It could explain your OverflowException

**Comment by Pilzinsel64** [comment]
Hm ... you're right. I thought i tried with Long-Variables too, but i was wrong. But i never had problems at converting long in int...
Now it works.
Sorry and thank you for your help. :)

**Comment by gpailler** [comment]
You're welcome
