### ISSUE TITLE
Getting the file hash.

### ISSUE THREAD

**Issue by Termir988** [gpailler/MegaApiClient#49]
Is it possible to get a hash of file Mega, to test it on a copy?

**Comment by gpailler** [comment]
There is no a real hash (MD5, SHA1...) stored on Mega servers (at least we cannot retrieve it if it exists).
The only checksum we have is a chunked CBC-MAC used to ensure file integrity. You can take a look on MegaAesCtrStream to see how it's computed.
If it's enough for your usage, we can expose this checksum on INode so you can compare it with local files

**Comment by greendrake** [comment]
What is the status of this? Is there any way to see _any_ hash of a file in Mega to verify that it downloads correctly?

**Comment by gpailler** [comment]
When you download a file, the hash is computed and validated so a downloaded file is always valid. If there is an issue with the hash, an exception is raised.
