### ISSUE TITLE
Issues trying to get it working on Windows 8

### ISSUE THREAD

**Issue by Johnwrnd** [gpailler/MegaApiClient#5]
Would be nice to have Windows 8/8.1 support of this project.

Regards
John

**Comment by ZiadJ** [comment]
@Johnwrnd Can you please confirm the api does not work in Windows 8 please? I don't see why it wouldn't.

**Comment by gpailler** [comment]
The library works fine on any OS (Windows 7/8/8.1/10). But the Framework 3.5 is required (not installed by default on Windows 8 and higher).
