### ISSUE TITLE
Slow Download/Upload

### ISSUE THREAD

**Issue by Pilzinsel64** [gpailler/MegaApiClient#50]
It isn't realy an issue i think, but i would ask you, if this is normal.

When I download or upload something to my MEGA Accounts via the Browser, It's realy fast (we have realy fast Internet). But when I download or upload something via your API-Client then it's realy slow often.
With your API-Client: Downloading/Uploading a little textfile or PNG takes between 10 seconds (this is realy rarely) and 60 seconds. Most it takes 30 seconds.
With the browser: Downloading/Uploading a little textfile or PNG takes one or two seconds.

I often take DownloadStream and UploadStream.

Fast download and upload would be imporant for my programm.
Simply tlease tell me, if the prblem is at your API-Client or at the MEGA-API.

I'm using the newest API-Version of you (v1.3.1).

Thanks,

Pilzinsel64

**Comment by gpailler** [comment]
Hello @Pilzinsel64 
The timings you found in your tests are not expected.
On AppVeyor, I run several unit tests and you can find the following timings for Download_ValidateStream_Succeeds test (to have an idea):
- On master branch, Login + Download of a ~500KB jpg file takes ~8s
- On develop branch, Download only of the same ˜500KB file takes ˜2.5s

The difference between master and develop is related to a big refactoring in unit tests and in the code but we are far from 30seconds.

Maybe you can test the following code and tell me the timing you have:
```
const string link = "https://mega.nz/#!ulISSQIb!RSz1DoCSGANrpphQtkr__uACIUZsFkiPWEkldOHNO20";

using (Stream stream = this.client.Download(new Uri(link)))
{
    Assert.Equal(523265, stream.Length);
}
```

You can also test latest develop package available on [AppVeyor](https://ci.appveyor.com/project/gpailler/megaapiclient/build/1.5.0.303/artifacts). There is few API breaks but we improved speed and stability.

**Comment by Pilzinsel64** [comment]
Hi.

I tried the 1.5.0-develop version and it works fine. Don't know why.

Thank you for your help! :-}

**Comment by gpailler** [comment]
Great!. I will try to merge Develop on master in few days/weeks (with other improvements) and I will release it on Nuget. I keep the issue open until the the release
