### ISSUE TITLE
Problems sending .zip file

### ISSUE THREAD

**Issue by jefersonkallynsr** [gpailler/MegaApiClient#53]
**Description**:
I'm trying to send files from the .zip extension, but to no avail. The upload of the file until happens, but when I download the file again a "Decoding Error" occurs when 99% of the download arrives and Mega does not return the file. The most interesting thing is that I got the same file that I'm having problems and I sent manually by the browser and everything went well. It may be my code, but I'm not sure I can send files from other extensions without further problems.

**Actual Behavior**:
The upload of the .zip file happens, however at the time of download an error is displayed by the Mega: "Decoding Error"

**Expected Behavior**:
The .zip file will download without problems.

**Steps to Reproduce**:

Zipping the file and sending:

    using (MemoryStream megaStream = new MemoryStream())
    {
        using (ZipArchive zip = new ZipArchive(megaStream, ZipArchiveMode.Create, true))
        {
            foreach (HttpPostedFileBase upload in uploads)
            {
                ZipArchiveEntry entry = zip.CreateEntry(upload.FileName, CompressionLevel.Fastest);

                using (Stream stream = entry.Open())
                {
                    upload.InputStream.CopyTo(stream);
                }
            }
        }

        /*
        Response.Buffer = true;
        Response.Clear();
        Response.ContentType = "application/zip";
        Response.AddHeader("content-disposition", "attachment; filename=Test.zip");

        Response.BinaryWrite(megaStream.ToArray());

        Response.Flush();
        */

        INode upload = await client.UploadAsync(megaStream, "Test.zip", pasta, new Progress<double>());
    }

**MegaApiClient Version**: Latest version

**Comment by gpailler** [comment]
Hello @jefersonkallynsr 
Probably you forgot to paste some part of the code because I don't know what `arquivo` variable is.
Could you try to save the zip archive into a file and upload this file (instead using the stream)?

**Comment by jefersonkallynsr** [comment]
I'm sorry @gpailler and thanks for answering me. Ignore this `arquivo`, the correct one is:

`INode upload = await client.UploadAsync(megaStream, "Test.zip", pasta, new Progress<double>());`

I'll try to do what you said and I'll come back with news.

NOTE: `pasta` is any node where the file will be sent.

**Comment by gpailler** [comment]
Ok great.
Maybe one think to check is to ensure the `megaStream` position is 0 before the call to UploadAsync.

**Comment by jefersonkallynsr** [comment]
Sorry for the delay @gpailler, you got it right in relation to my MemoryStream being in the wrong position. I was sending the stream in the last position, so I gave the Mega error. I apologize for the inconvenience and thank you very much for the help and for the plugin.
