### ISSUE TITLE
DownloadFileAsync not reporting progress.

### ISSUE THREAD

**Issue by RhysRah2212** [gpailler/MegaApiClient#56]
I'm trying to download this file from a specific URL asynchronously so I can update the UI on the download, as that's what you should do. I've made some code, but whilst it does download the file without blocking the UI thread, it doesn't update any progress.

```
Dim clientctgp As New MegaApiClient()
clientctgp.Login("username", "password") 'My actual details are entered here
Dim progress As New Progress(Of Double)(Function(p) lblSecondary.Text = String.Format("{0}% complete", p))
clientctgp.DownloadFileAsync(New Uri("https://mega.nz/#!RvRkiYqL!Y7xb9v5Dwd_IKcFUgewnVYDPDaLmDjA8TKD6PUQaz8E"), Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) & "\ctgpr.zip", progress)
```

It's probably me being stupid, but I'm new to the API, so I'm trying to get to grasps with it. Help would be appreciated. Thanks :) 

EDIT: This code is VB.net, but i can translate c# code if needed.

**Comment by gpailler** [comment]
Hello @RhysRah2212 

I tried the following code (in a WPF sample app) and it works properly. Did you tried to add a breakpoint in the callback to see if you receive the progress?

```
private void Button_Click(object sender, RoutedEventArgs e)
{
  var clientctgp = new MegaApiClient();
  clientctgp.Login("username", "password");

  clientctgp.DownloadFileAsync(
    new Uri("https://mega.nz/#!RvRkiYqL!Y7xb9v5Dwd_IKcFUgewnVYDPDaLmDjA8TKD6PUQaz8E"),
    "ctgpr.zip",
    new Progress<double>(this.UpdateProgress));
}

private void UpdateProgress(double d)
{
  this.lbl.Text = string.Format("{0}% complete", d);
}
```

**Comment by RhysRah2212** [comment]
Thanks @gpailler, that works perfectly. 

This isn't as urgent, but is it possible to get file sizes from a mega URL? I want to track download speeds with the download as well, so getting the filesize from there (as it is updated sometimes) would be the better option.

Cheers.

**Comment by gpailler** [comment]
You can call `INodeInfo GetNodeFromLink(Uri uri)` to retrieve details about the file (name/size/dates...)

**Comment by RhysRah2212** [comment]
Thanks, I've got what I needed now. Cheers 👍
