### ISSUE TITLE
Error at downloading file

### ISSUE THREAD

**Issue by Pilzinsel64** [gpailler/MegaApiClient#57]
I'm using v1.5.0 of the client.

I made a programm where I'm using this client.
A user got a error message. This message tells me an error at executing "Await MegaApiClient.DownloadAsync".

Error-Message:
https://gyazo.com/03cc2152a04e9191b3042b2cf4922fc8

This Error happens only for him, but i realy don't know why.

Would you check out, please, why this could happen?

Thanks

**Comment by SeppPenner** [comment]
I guess, it's impossible for the developer to help you if you are not giving a piece of code you are using... @Pilzinsel64

**Comment by gpailler** [comment]
According the screenshot, it's maybe something related to the date. What local do you use? Could you attach a sample to reproduce this issue?

**Comment by Pilzinsel64** [comment]
The problem is that this problem is only for one person and that isn't me. Maybe it isn't MegaApiClient.

By the way, why the MegaApiClient upload files with an invalid file checksum sometimes?

Here an Example:

I upload five memory streams:
https://gyazo.com/caa245e9020b5c3390eedb156fc38308

The 5th file has always a checksum when I try to download it.

After this I changed the name of the 4th file from 'thumbnail_small'  to 'thumbnail' and then the 4th file has the checksum error. Why? What do I wrong?

And this is only ONE example.

**Comment by gpailler** [comment]
About your first issue, could you ask this person which local is used on the computer?

About your issue with checksums, I cannot help you without a sample or at least some code. You said the 5th has a checksum error. You notice this error when you download it through this library, through the Mega website?

You said it's not really random so you can probably post a small code to reproduce the issue.

Thanks

**Comment by Pilzinsel64** [comment]
The first issue:

He made a test and got some informations about. Here is the result:
http://www.userbenchmark.com/UserRun/4257414

And about the second issue:

I only load a Image to a MemoryStream. Then I upload it.

No, I can't download it using MEGA in the Browser. The file has a checksum error wich happens at uploading. But I get no error at uploading.
First when I download the file, it can't be decrypted.

Yes, it seems not realy random, but If I change small things, it's working fine or an another file has the checksum error. Like if I change the filename.

But I solved the problem.
I just created two new MemoryStream where I copied the content of the first two MemoryStreams. After uploading the new two MemoryStreams the files haven't a checksum error.
Probably the MemoryStream should be untuched.

**Comment by gpailler** [comment]
About the first issue, you said the error happens only for him. It means you don't have the issue if you try to download the same file? Could you ask the user to share the file through Mega and send me the download link (privately if you prefer, email: gregoire___pailler.fr).

About your second issue, I'm glad you solved the issue by copying streams content. So the issue was probably related to the first streams. Could you check the streams were reset to position 0 before using them with Upload() method?

**Comment by Pilzinsel64** [comment]
The first issue:
This could be a problem, because on the server a hundreds of files.
But I will add a log-writer to see wich file it is.
I notify you, when I get the result.

And the second issue:
Oh. Yes, that is the problem! So, I just have to set the position to 0.
Thank you very much!
