### ISSUE TITLE
Improvement: Possibility to see the already uploaded bytes (Get the upload progress)

### ISSUE THREAD

**Issue by SeppPenner** [gpailler/MegaApiClient#58]
It would be really nice to have an event that notifies you on the uploading progress (Would be good to visualize the upload progress in a ProgressBar in the GUI).

As an example to clearify what I mean, take a look at the GDrive Api V3:
[https://developers.google.com/api-client-library/dotnet/guide/media_upload](https://developers.google.com/api-client-library/dotnet/guide/media_upload)

with the following code:
`insertRequest.ProgressChanged += Upload_ProgressChanged;`

**Comment by gpailler** [comment]
Hello @SeppPenner 
If you use .Net version > 4.0, you can use the async versions of the methods. These methods use a IProgress as extra argument and you can retrieve progression.

For .Net version <= 4.0, you can follow this Wiki page to retrieve progression: https://github.com/gpailler/MegaApiClient/wiki/Retrieve-progression-of-an-upload-or-download

**Comment by SeppPenner** [comment]
Hi, @gpailler Thank you for the information. Must have overseen this. I'm using .Net 4.6.2 👍
