### ISSUE TITLE
Can i check upload speed ?

### ISSUE THREAD

**Issue by ShadyNagy** [gpailler/MegaApiClient#59]
is there function to check upload speed after upload ?

thanks for your help and great work hope soon .netcore supported

**Comment by gpailler** [comment]
There is no builtin function to retrieve upload speed (during upload or after it) but you can easily implement it, depending of your needs.
- For .Net 4.0, you can tweak the `ProgressionStream` (https://github.com/gpailler/MegaApiClient/wiki/Retrieve-progression-of-an-upload-or-download).
- For > .Net 4.0, you can pass a `IProgress` implementation to the Upload methods

About .netcode, it's in progress. I'm currently investigating few failed Unit Tests but it should be available soon for tests.

**Comment by ShadyNagy** [comment]
ok Thanks for your help
