### ISSUE TITLE
Whether  provide other function can download link file?

### ISSUE THREAD

**Issue by toasttsao** [gpailler/MegaApiClient#6]
Whether provide   downloadfile method parameters from uri?

Regards
Toast

**Comment by gpailler** [comment]
I don't really understand your request. Can you explain and add some details?

**Comment by toasttsao** [comment]
Sorry my english not good,
i mean Whether other functions provided MEGA can download additional files, not just self own file ?

Regards
Toast

**Comment by gpailler** [comment]
With the library, you can download any file stored by specifying the associated Node. You want to be able to download a whole folder? Can you describe an example or what you except?

**Comment by toasttsao** [comment]
That is how direct download files via URL? 
https://mega.co.nz/#!CtFjGZwT!sxz1O6e-m7E1L7VFLhPo-kYq7maTb6OXxSjaJSNSr50

**Comment by gpailler** [comment]
Add method to download file from Mega URI

**Comment by toasttsao** [comment]
thanks for your detailed answer

**Comment by zeeshan47** [comment]
please tell me the code how to download the file  as you show in example how to upload
