### ISSUE TITLE
Help with installation.

### ISSUE THREAD

**Issue by CodeXLmao** [gpailler/MegaApiClient#60]
This is an issue for me, I have not used things like this before, Nodes etc. Got it to install through NuGet and have used the reference - Newtonsoft but I can't get:
MegaApiClient client = new MegaApiClient();
to work
says it's not referenced when I have referenced it. Could you show a clear installation on how to get the api working on a WinForm?

**Comment by gpailler** [comment]
Hello,

You retrieved MegaApiClient through Nuget? In this case, MegaApiClient and Newtonsoft should be referenced automatically in your project, no need to manually reference the libraries

**Comment by CodeXLmao** [comment]
Doesn't seem to work. I have installed it but I can't use it with
using MegaApiClient;
that doesn't work

**Comment by CodeXLmao** [comment]
I have tried uninstalling and reinstalling and it still doesn't work. Does the version of Visual Studio Matter?

**Comment by gpailler** [comment]
VS version should not have any impact
The namespace is `CG.Web.MegaApiClient`, not only 'MegaApiClient'.
Please attach a sample project with your issue for further investigation

**Comment by CodeXLmao** [comment]
I will give that a try now, thank you

**Comment by CodeXLmao** [comment]
Worked. Thank you
