### ISSUE TITLE
Sorry Me Again

### ISSUE THREAD

**Issue by CodeXLmao** [gpailler/MegaApiClient#61]
How would I go about downloading a file from a URL, I looked at some of the code that you have put and I can't make full sense of it. 

I am new to Nodes etc, I want to Download a file (which includes the Decryption Key) to the PC 

Thanks in advance.

**Comment by gpailler** [comment]
You want to download a file and you have the URL right?
You should try the following
```
const string Username = ....;
const string Password = ....;
const string FileToDownload = "https://mega.co.nz......";

MegaApiClient client = new MegaApiClient();
client.Login(Username, Password);

// Retrieve name, size... of the file
var nodeInfo = client.GetNodeFromLink(new Uri(FileToDownload));

// Download file to the current folder
client.DownloadFile(new Uri(FileToDownload, nodeInfo.Name));
```

You can also use `client.Download(...)` method to download a file as a Stream and retrieve progression

**Comment by CodeXLmao** [comment]
How would I go about downloading as a stream because I want to use a progression bar

**Comment by CodeXLmao** [comment]
Can't you use download file sync as you would with webclient

**Comment by gpailler** [comment]
To download a file sync:
`client.DownloadFile(new Uri(FileToDownload), nodeInfo.Name);`

To download a file async with progression:
``` 
IProgress<double> progress = new Progress<double>(x => Console.WriteLine(x));
client.DownloadFileAsync(new Uri(FileToDownload), nodeInfo.Name, progress);
```

**Comment by CodeXLmao** [comment]
Was just wondering, if there was a way of telling it to put the download in a specific folder. at the moment it just lands in the directory of the application

**Comment by gpailler** [comment]
You can use a stream to save the file in a specific folder
```csharp
var destination = @"SubFolder\MyFile.jpg";
using (var stream = client.Download(node))
{
  using (var fileStream = new FileStream(destination, FileMode.CreateNew))
  {
    stream.CopyTo(fileStream);
  }
}
```
