### ISSUE TITLE
Missing XML comments in packaged library

### ISSUE THREAD

**Issue by Sergio0694** [gpailler/MegaApiClient#62]
**Description**:

The library itself contains the XML comments on all the exposed members, but it seems the .csproj file isn't configured to actually generate the XML documentation file when building the output .dll file.
So, you don't actually see any XML comments when referencing the library from NuGet (or MyGet).
It should be possible to fix this by just ticking the "XML docs file" checkbox in the csproj Properties window.

**MegaApiClient Version**: tested with the current .NET Standard preview release.

Thank you again for your work! 😄

**Comment by gpailler** [comment]
Thanks. I forgot to enable XML generation when I switched to new csproj format
