### ISSUE TITLE
Increase TCP send size

### ISSUE THREAD

**Issue by GSPP** [gpailler/MegaApiClient#65]
As a user of the backup tool Duplicati I have discovered a possible inefficiency in the way Mega uploads are made: https://github.com/duplicati/duplicati/issues/2647. I'm now reporting this issue here because it appears to be fixable only in MegaApiClient. Here is the text unmodified:

<hr>

Using Process Monitor and Wireshark I watched Duplicati upload to Mega. I did this because the program did not fully use all available upload speed of my connection. This could be due to the Mega servers not taking the data faster. But the logs I captures suggest that the `MegaApiClient` could be more efficient.

It seems to send in 8KB chunks:

![image](https://user-images.githubusercontent.com/12032350/29456754-8ab4870a-8417-11e7-8248-330b3278c618.png)

But how does the OS physically send those chunks?

![image](https://user-images.githubusercontent.com/12032350/29456787-b14599b8-8417-11e7-9103-41cae1df44e0.png)

I have marked one send/ACK cycle. It looks like it is introducing a boundary after 8KB and waiting for acknowledgement. It also sets the `PSH` flag indicating that this is deliberate. Also note, that the next 8KB send batch waits for the ACK to fully arrive as can be seen by the time stamps.

These findings suggest that uploading would be more efficient if bigger buffers were used. I think increasing to 64KB buffers is a no-brainer. I could see far bigger sizes make sense. For bulk transfers I believe it is beneficial to enable nagling which might get rid of these boundaries entirely.

That being said I don't know if this is fixable since the actual uploading seem to happen in `CG.Web.MegaApiClient.WebClient.PostRequest` which is third-party code. I still wanted to put this issue here so that it can be understood and tracked at least. Also, other backends might be affected.

This is 2.0.2.1_beta_2017-08-01 on Windows x64.

<hr>

So it seems that uploads could benefit from much larger buffer sizes.

**Comment by gpailler** [comment]
Thanks for the report.
You're right, the 8KB buffer is way to small and has a negative impact on performance. I will change the default value to 64KB for the next release.

In the meantime, since the version 1.5.0, you can customize the buffer size (and other options) using the following syntax when creating the MegaApiClient instance:
```csharp
var instance = new MegaApiClient(new Options(bufferSize: 65536));
``` 

You can also provide your own WebClient custom implementation:
```csharp
IWebClient webCLient = new MyWebClient();
var instance = new MegaApiClient(webClient);
```

About nagling, I need to investigate deeper. What is your upload speed because on my side, my upload limits my tests.

**Comment by GSPP** [comment]
I have about 6 mbits upload. Ideally, the new version would land in Duplicati and I'd test it that way.

I'm surprised to see these PSH boundaries at all. I was under the impression that streaming transfers of data are handled adequately by the kernel. Not sure how user mode is supposed to deal with this. I *think* nagling should be on. This should remove all PSH boundaries. But then, there might be a 200ms additional latency at the end of the upload. The Windows TCP API has no way to flush outstanding data (at least that was my conclusion when researching this a while ago). So maybe nagling should be off and huge buffers must be used knowing that each buffer will cause one roundtrip latency. A disappointing state of affairs in my opinion.
