### ISSUE TITLE
Optimization opportunity in MegaAesCtrStream

### ISSUE THREAD

**Issue by GSPP** [gpailler/MegaApiClient#66]
As a user of the backup tool Duplicati I have discovered a possible inefficiency in the way Mega uploads are made: https://github.com/duplicati/duplicati/issues/2647#issuecomment-323341813. I'm now reporting this issue here because it appears to be fixable only in MegaApiClient. Here is the text unmodified:

<hr>

I also just notice that download speed with the Mega backend ist 1.4MB/sec only driving one CPU core to 100%. This is because of very inefficient code. Most call stacks I sampled look like this:

![image](https://user-images.githubusercontent.com/12032350/29458956-eb9574b2-8421-11e7-8ecb-a0d5259c7969.png)

Just letting you know. See https://github.com/gpailler/MegaApiClient/blob/master/MegaApiClient/MegaAesCtrStream.cs. The Read method looks very fragile. A few possible correctness problems come to mind as well (not sure).

<hr>

It seems that `Any` is called for each byte being processed. I'm not sure what the best fix would be but I wanted to report this issue to the project.

**Comment by gpailler** [comment]
Any() was used each 16 bytes to determine if the current position in the stream was on a chunk bondary. The complexity was O(n) so bigger was the file, slower was the code.
The list is replaced with an HashSet.

Before/After
![image](https://user-images.githubusercontent.com/3621529/30196157-a6199522-9488-11e7-87e9-292eb95d9955.png)

**Comment by gpailler** [comment]
I also optimized the encryption part in the scope of this issue

![image](https://user-images.githubusercontent.com/3621529/30197260-e3c19476-9490-11e7-94b4-86cb8bb42891.png)

**Comment by gpailler** [comment]
@GSPP Could you download binaries from https://ci.appveyor.com/project/gpailler/megaapiclient/build/1.6.1.363/artifacts and replace the MegaApiClient.dll library used in your Duplicati instance with this new version?
This build includes 64KB BufferSize and CPU usage optimization changes

**Comment by GSPP** [comment]
I needed to add a binding redirect to get the latest version to load. But then I get

```
Fatal error
System.MissingMethodException: Method not found: 'Void CG.Web.MegaApiClient.MegaApiClient.Login(System.String, System.String)'.
   at Duplicati.Library.Main.BackendManager.List()
   at Duplicati.Library.Main.Operation.FilelistProcessor.RemoteListAnalysis(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.FilelistProcessor.VerifyRemoteList(BackendManager backend, Options options, LocalDatabase database, IBackendWriter log, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.PreBackupVerify(BackendManager backend, String protectedfile)
   at Duplicati.Library.Main.Operation.BackupHandler.Run(String[] sources, IFilter filter)
```

So it looks like the Duplicati team need to make code changes to restore compatibility before I can test. @kenkendk

**Comment by kenkendk** [comment]
The latest version seems to be 1.6.0:
https://www.nuget.org/packages/MegaApiClient/

Not sure how I can update ? Also, it is unexpected that a minor update (1.6.0 -> 1.6.1) would have a breaking API change. Am I using a deprecated `Login` method?

**Comment by gpailler** [comment]
@GSPP Which version of Duplicati do you use?

Duplicati 2.0.2.1 (version from https://www.duplicati.com/download) uses MegaApiClient 1.3.1.269 and there is some API breaks between 1.3 and 1.6.

I checked Duplicati releases and @kenkendk updated MegaApiClient version in https://github.com/duplicati/duplicati/releases/tag/v2.0.2.2-2.0.2.2_canary_2017-08-30. 
I downloaded this version and replaced MegaApiClient.dll (with \lib\net45\ version from the nupkg). Seems it works without any binding redirect.

Could you test with canary build?

**Comment by GSPP** [comment]
Trying with that release and the latest release and with replaced library results in

```
Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Not sure how to address that on my end.

**Comment by gpailler** [comment]
Could you try the following steps:
* Download and extract: https://github.com/duplicati/duplicati/releases/download/v2.0.2.2-2.0.2.2_canary_2017-08-30/duplicati-2.0.2.2_canary_2017-08-30.zip
* Download and extract: https://ci.appveyor.com/api/buildjobs/ta2fa92gyb8ffau7/artifacts/artifacts%2FMegaApiClient.1.6.1-66-improve-363.nupkg
* Copy the file `MegaApiClient.1.6.1-66-improve-363\lib\net45\MegaApiClient.dll` to `duplicati-2.0.2.2_canary_2017-08-30\`
* Launch Duplicati by running `duplicati-2.0.2.2_canary_2017-08-30\Duplicati.GUI.TrayIcon.exe`

**Comment by gpailler** [comment]
1.6.1 released
