### ISSUE TITLE
ApiException in Release mode (UWP) when calling LoginAsync

### ISSUE THREAD

**Issue by Sergio0694** [gpailler/MegaApiClient#69]
**Description**: I'm using the library in my UWP application and it works perfectly fine in debug mode. When compiled in Release mode though, I get the following exception:

![image](https://user-images.githubusercontent.com/10199417/29997264-1b3c7d2a-900f-11e7-8d0c-41b568f2cfe8.png)

> Note the exception itself looks to be thrown in an auto-generated file, no idea what's up with it

It only happens in Release mode (when the .NET Native toolchain is enabled) when I call the `MegaApiClient.LoginAsync` method (I've double checked, the credentials are right).
As a result, I can't login at all in Release mode.

**MegaApiClient Version**: the official 1.6.0 package from NuGet

Hope this helps! 😄

**Comment by gpailler** [comment]
It's odd because MegaApiClient is not dependant of the compilation mode (Release version only in the nupkg) and the behavior should be the same between Debug or Release compilation. Maybe it's related to a dependency. 

Could you show the exception details (message, stack trace, error code)?

**Comment by Sergio0694** [comment]
@gpailler I know the package is in Release only mode, but keep in mind that when compiling a UWP app (not a library) in Release, the .NET Native compiler kicks in, and it can sometimes cause glitches (specifically with the metadata/serialization part of the code).

Upon further investigation I think I found the cause of the issue:
![image](https://user-images.githubusercontent.com/10199417/30004052-861c887e-90c8-11e7-9445-784f61cb9a94.png)
The .NET Native compiler has some known issues with dynamic variables, so this code was working fine in Debug mode but not in release, as the metadata needed for the dynamic type was missing.
I've tried to manually include it in the Default.rd.xml file but it didn't work, so I ended up just doing this:
```csharp
MegaApiClient.AuthInfos deserialized = JsonConvert.DeserializeObject<MegaApiClient.AuthInfos>(json);```

This seems to have fixed the issue, so you might want to add a disclaimer for the right deserialization method to use in the readme file so other user won't have to deal with this problem again 😄

**Comment by gpailler** [comment]
Thanks. for the feedback I will update the README
