### ISSUE TITLE
Upload use too much processor time

### ISSUE THREAD

**Issue by helpme1c** [gpailler/MegaApiClient#70]
**Description**:
*what are you trying to do*
I use MegaApiClient in my program for upload file to mega.nz.
**Actual Behavior**:
*what happens*
Program use ~20% processor time on upload file.
**Expected Behavior**:
*what should happen* 
Other libs (e.g. google drive c# lib) use only 1-3% for this operation.
**MegaApiClient Version**: 1.6.0.0

**Comment by gpailler** [comment]
One of the main difference between GDrive and Mega is data is encrypted on client side.
But there is probably room for improvement. 

CPU usage is related to #66.

**Comment by helpme1c** [comment]
Thanks for your answer. I thought as much.

**Comment by helpme1c** [comment]
By the way Chrome on uploading (with encrypt) to mega.nz use only 5% processor time.

**Comment by gpailler** [comment]
Related to #66

**Comment by gpailler** [comment]
Duplicate of #66
