### ISSUE TITLE
Upload through MegaApiClient too long (in comparison with browser upload)

### ISSUE THREAD

**Issue by helpme1c** [gpailler/MegaApiClient#71]
**Description**:

*what are you trying to do*
I use MegaApiClient for upload file to mega.nz

**Actual Behavior**:

*what happens*
Upload through MegaApiClient too long (in comparison with browser upload). In my case the difference is tenfold. Perhaps this is also related with unoptimized encrypt?

**MegaApiClient Version**: 1.6.0.0

**Comment by helpme1c** [comment]
I realized that this is due to the default buffersize (8 kb) and I can override this throug Options.

**Comment by gpailler** [comment]
Great. Thanks for the feedback. 
he default buffersize will be changed to 64KB in next version 1.6.1 (related to #65 ).
Which value do you use?

**Comment by helpme1c** [comment]
First my buffersize was default value (8KB). Then i set it to 64KB and nothing changed. Unfortunately upload too long (in comparison with browser) even with buffer size 64KB.

Now i think than buffer size is not reason so long upload. I tried increase chankpacksize value and nothing changed too.

**Comment by gpailler** [comment]
What is the size of the file you're trying to upload? Could you try with a small file (10MB for example). If you have good upload performance with a small file (and chunksize = 64KB) then this issue is probably the same as #66.

**Comment by helpme1c** [comment]
File size ~50MB. On small files (~5MB) difference between MegaApiClient and browser upload ~2 times.

**Comment by gpailler** [comment]
@helpme1c Could you download the binaries from https://ci.appveyor.com/project/gpailler/megaapiclient/build/1.6.1.363/artifacts and test again CPU usage and Upload speed?

Thanks

**Comment by helpme1c** [comment]
Results.

1. Upload 50MB file through browser take ~1.5 minutes and ~5% processor time.

2. Upload 50MB file with OLD version lib and 64 KB buffer size take ~3.20 minutes and ~20% processor time in peaks.

3. Upload 50MB file with NEW version (1.6.1.363) lib and 64KB buffer size take ~ 2 mintes and 10% processor time in peaks.

**Comment by gpailler** [comment]
Great. It's already a good improvement (in speed and CPU). Could you do a last test with a bigger buffersize (try 1MB for example)

**Comment by helpme1c** [comment]
I checked it. Bigger buffer size in my case not increase speed.

**Comment by gpailler** [comment]
Ok thanks. I will rerun a tracing session to try to find another bottleneck

**Comment by gpailler** [comment]
According tracing session, there is no bottleneck anymore in the code. Next improvement is to implement parallel upload to use maximum of the network bandwith. #75 is created
