### ISSUE TITLE
Cannot Access the BufferSize variable 

### ISSUE THREAD

**Issue by B1QB0SS** [gpailler/MegaApiClient#72]
**Description**:

Changing the default BufferSize 

**Actual Behavior**:

i tried this first MegaApiClient.BufferSize (it doesn't exist / private) 
and tried using an instance of MegaApiClient but i can't seem to find it

**tried 1.5 , 1.6, 1.6.1-66 (linked in the previous issue) **:

**Comment by gpailler** [comment]
You should use the following syntax to change the BufferSize
```
var instance = new MegaApiClient(new Options(bufferSize: 65536));
```

**Comment by B1QB0SS** [comment]
wow that was a fast reply lol 

i actually found out and was about to mark this Solved :D
