### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by CodeXLmao** [gpailler/MegaApiClient#73]
Got download working for a few downloads. Trying to get download with stream working with a download at 8GB and it's not working, the same code is working for other downloads, I am not sure why this is happening.
Example Code Below:

```
const string FileToDownload = "Have Removed Link";
var nodeInfo = client.GetNodeFromLink(new Uri("Have Removed Link"));


IProgress<double> progress = new Progress<double>(x => progressBarControl1.EditValue = x);
progressBarControl1.EditValueChanged += progressBarControl1_EditValueChanged;
progressBarControl1.Text = progressBarControl1.EditValue.ToString();

client.DownloadFileAsync(new Uri(FileToDownload), nodeInfo.Name, progress);
labelControl2.Text = labelControl2.Text + nodeInfo.Name;

```

**Comment by gpailler** [comment]
What do you mean by it's not working. Do you have any exception in VS output window?
Does it work if you use DownloadFile instead the Async version ?

**Comment by CodeXLmao** [comment]
Sorry for not responding, been busy. I will see if it works with the downloadfile without async but if it does work without async then I will be stuck with no progression and the only output I get from VS is Bandwidth Limit Exceeded which I have looked around about and noone really talks about it.

**Comment by CodeXLmao** [comment]
Any help man?

**Comment by gpailler** [comment]
I tried to download a large file and I faced the same Bandwidth error 509.
It's not related to MegaApiClient library but new Mega limitation for free accounts (https://www.reddit.com/r/megalinks/comments/6f0z7h/meta_megadownloader_and_megatools_are_no_longer/)
