### ISSUE TITLE
How to query size of a folder in mega?

### ISSUE THREAD

**Issue by SriramSakthivel** [gpailler/MegaApiClient#77]
Hi,

I'm trying to query the size of a folder in mega. I found that `Node` has `Size` property and used it.
But Size property always returns zero.

    IEnumerable<INode> nodes = await client.GetNodesAsync();
    var someNode = nodes.First(x => x.Name == "FolderName");
    Console.WriteLine(someNode.Size);// Returns zero ?

Again, how do I query the size of a folder?

Version : "1.6.1.368

**Comment by gpailler** [comment]
For a folder, the size is always 0. Only files have a real size.
To compute the size of a folder, you should write a recursive method to sum the size of all files, subfiles...
You should iterate on all nodes and use the `ParentId` property on `INode` in this method.

If you write such method, I'll glad to add it on `INode` (or you can propose a Pull Request).

**Comment by SriramSakthivel** [comment]
I did wrote such a method which gets the job done. Just looking for any out of the box way.

Tried to raise a PR but sadly project did not load for me in VS 2015 not sure why. I'm just posting the code here which might help future readers. Or you can add it to the library!

    public static class NodeExtensions
    {
        public static async Task<long> GetFolderSizeAsync(this INode node, MegaApiClient client)
        {
            if (node.Type != NodeType.Directory)
            {
                throw new InvalidOperationException("node is not a Directory");
            }

            long folderSize = 0;
            var children = await client.GetNodesAsync(node);
            foreach (var childNode in children)
            {
                if (childNode.Type == NodeType.File)
                {
                    folderSize += childNode.Size;
                }
                else if (childNode.Type == NodeType.Directory)
                {
                    long size = await GetFolderSizeAsync(childNode, client);
                    folderSize += size;
                }
            }
            return folderSize;
        }
    }

I've smoke tested it and that seem to work fine.

**Comment by gpailler** [comment]
Thanks for the function. The project needs VS2017 because MegaApiclient is compiled against .Net core too.

I will add your function on the next release. I wrote an updated version with few improvements (it's a non async version)
* Method is compatible with all types except File (So you can get the Trash size)
* `GetNodes()` is called only once to improve performances (this method send a request to the Mega servers so it's better to cache the result). And Mega servers returns list of all nodes so it can be huge (when you call `GetNodes(INode parent)`, it's filtered on client side)

```csharp
  public static class NodeExtensions
  {
    public static long GetFolderSize(this INode node, IMegaApiClient client)
    {
      var allNodes = client.GetNodes();
      return node.GetFolderSize(allNodes);
    }

    public static long GetFolderSize(this INode node, IEnumerable<INode> allNodes)
    {
      if (node.Type == NodeType.File)
      {
        throw new InvalidOperationException("node is not a Directory");
      }

      long folderSize = 0;
      var children = allNodes.Where(x => x.ParentId == node.Id);
      foreach (var childNode in children)
      {
        if (childNode.Type == NodeType.File)
        {
          folderSize += childNode.Size;
        }
        else if (childNode.Type == NodeType.Directory)
        {
          long size = childNode.GetFolderSize(allNodes);
          folderSize += size;
        }
      }

      return folderSize;
    }
  }
```

**Comment by gpailler** [comment]
On 1.6.2
