### ISSUE TITLE
Proxy Authentification

### ISSUE THREAD

**Issue by Pilzinsel64** [gpailler/MegaApiClient#78]
Hi!

Is it possible to set the authentification (username and password) for the proxy?
Because MegaApiClient can't use the Proxy without the credentails.

If not, can you implement it, please?

Thanks.

**Comment by gpailler** [comment]
Could you test to configure the proxy from your app configuration?
Probably something like https://stackoverflow.com/a/9839120 should work

**Comment by Pilzinsel64** [comment]
It is working now, but I find an another way on the site from the link you posted.

**Comment by gpailler** [comment]
Great! Could you share the details so I will create/update the README or the FAQ?

Thanks

**Comment by Pilzinsel64** [comment]
Sure.
Just set the crede tails via:
WebRequest.DefaultWebProxy.Credentials = New NetworkCredentails("Username", "Password)

**Comment by gpailler** [comment]
Thanks
