### ISSUE TITLE
Shared key

### ISSUE THREAD

**Issue by BigOak** [gpailler/MegaApiClient#8]
Hi,

When working with shared folders, I  met a a case in which the key is in this format:
"k" : "{owner1}:{key1}/{owner2}:{key2}"
So, on the Node class, we need to handle this case by getting one key:
var searializedKey = SerializedKey;
if (serializedKey.Contains("/")) {
                        serializedKey = serializedKey.Substring(0, serializedKey.IndexOf("/"));
                    }

And when retrieving shared masterkey, I think you miss this part otherwise the file attribute cannot be decrypted successfully (folder is OK):
...
if (nodesResponse.SharedKeys != null) {
...
if (this.Type == NodeType.Directory) {
                            DecryptedKey = masterKey;
                        } else if (this.Type == NodeType.File) {
                            DecryptedKey = Crypto.DecryptKey(encryptedKey, masterKey);
                        }
...

Thanks a lot for this great lib :+1:

**Comment by gpailler** [comment]
Hello @BigOak 

Can you propose a pull request? Seems you have already digged the library to provide a fix.

Thanks a lot

**Comment by BigOak** [comment]
I'm not really acquainted with GitHub, so I think it is faster to send you the code:

public void OnDeserialized(StreamingContext ctx) {
            byte[] masterKey = (byte[])((object[])ctx.Context)[0];
            GetNodesResponse nodesResponse = (GetNodesResponse)((object[])ctx.Context)[1];

            this.LastModificationDate = OriginalDateTime.AddSeconds(this.SerializedLastModificationDate).ToLocalTime();

            if (this.Type == NodeType.File || this.Type == NodeType.Directory) {
                var searializedKey = SerializedKey;
                int splitPosition = searializedKey.IndexOf(":", StringComparison.InvariantCulture);
                var str = searializedKey.Substring(splitPosition + 1);
                byte[] encryptedKey = null;
                try {
                    encryptedKey = str.FromBase64();
                } catch {
                    // There are cases that the Key has strange format and cannot be convert to base32
                    // for ex: { ...,"k": "9sVHkIiY:PRb1gXULkZUiXI1xWDh46g/o5tGQTgL:Fv0FuJAbpAYTdczE7To5Mw", ...}
                    if (str.Contains("/")) {
                        str = str.Substring(0, str.IndexOf("/"));
                    }
                    encryptedKey = str.FromBase64();
                }

                this.DecryptedKey = Crypto.DecryptKey(encryptedKey, masterKey);
                this.Key = this.DecryptedKey;

                // If node is shared, we need to retrieve shared masterkey
                if (nodesResponse.SharedKeys != null) {
                    string owner = searializedKey.Substring(0, splitPosition);
                    GetNodesResponse.SharedKey sharedKey = nodesResponse.SharedKeys.FirstOrDefault(x => x.Id == owner);
                    if (sharedKey != null) {
                        masterKey = Crypto.DecryptKey(sharedKey.Key.FromBase64(), masterKey);

                        if (this.Type == NodeType.Directory) {
                            DecryptedKey = masterKey;
                        } else if (this.Type == NodeType.File) {
                            DecryptedKey = Crypto.DecryptKey(encryptedKey, masterKey);
                        }

                        this.Key = Crypto.DecryptKey(encryptedKey, masterKey);
                    }
                }

                if (this.Type == NodeType.File) {
                    // Extract Iv and MetaMac
                    byte[] iv = new byte[8];
                    byte[] metaMac = new byte[8];
                    Array.Copy(this.DecryptedKey, 16, iv, 0, 8);
                    Array.Copy(this.DecryptedKey, 24, metaMac, 0, 8);
                    this.Iv = iv;
                    this.MetaMac = metaMac;

                    // For files, key is 256 bits long. Compute the key to retrieve 128 AES key
                    this.Key = new byte[16];
                    for (int idx = 0; idx < 16; idx++) {
                        this.Key[idx] = (byte)(this.DecryptedKey[idx] ^ this.DecryptedKey[idx + 16]);
                    }
                }

                Attributes attributes = Crypto.DecryptAttributes(this.SerializedAttributes.FromBase64(), this.Key);
                this.Name = attributes.Name;
            }
        }

**Comment by gpailler** [comment]
I will integrate and test your code for integration

**Comment by gpailler** [comment]
I implemented your changes to deserialized shared file (+UT) but I'm unable to reproduce the case with the key format you described ("k" : "{owner1}:{key1}/{owner2}:{key2}"). Can you give me more details how I can get this kind of key?
I would like to add a UT for this case.

**Comment by gpailler** [comment]
I finally identified why we can have multiple keys in SerializedKey attribute. This can occur when you share a subfolder from a folder already shared. Both keys seems to work to deserialize node so we use always the first key
