### ISSUE TITLE
Problem with upload big file (2.5 gb)

### ISSUE THREAD

**Issue by milkin-vl** [gpailler/MegaApiClient#80]
Cant upload file with size 2.5 gb to mega.nz.

First, lib MegaApiClient upload with speed 1.3 megabyte per second, but then after 30 minutes upload is stopped and upload traffic is freeze.

After another 60 minutes upload broken with errors without any description.

**Comment by helpme1c** [comment]
Lib version 1.6.1.

**Comment by gpailler** [comment]
This issue is identified. There was a bug in MegaApiClient and the maximum upload size was 2GB

**Comment by milkin-vl** [comment]
Great news!

**Comment by gpailler** [comment]
1.6.3 released
