### ISSUE TITLE
is there an easy way to traverse directories

### ISSUE THREAD

**Issue by RickySan65** [gpailler/MegaApiClient#83]
is there an easy way to traverse directories? i can get them from nodes, but now do i know which sub directory belongs to another etc.

eg.
folder1\test1\test2

**Comment by gpailler** [comment]
To achieve this goal, you have `ParentId` property on each node.
So to get all subfolders of folder1, you can write
```csharp
var allNodes = client.GetNodes().ToArray();
var parentNode = allNodes.Single(x => x.name == "folder1");
var subFolders = allNodes.Where(x => x.ParentId == parentNode.Id);
```

**Comment by RickySan65** [comment]
Figured it out :) thanks
