### ISSUE TITLE
MegaApiClient.GetAccountInformationAsync just broke (across different versions/builds)

### ISSUE THREAD

**Issue by Sergio0694** [gpailler/MegaApiClient#86]
**Description**:

It looks like the `MegaApiClient.GetAccountInformationAsync` has stopped working for me, both with the latest library version and with an older version I have in a production build of my app. Here's a screen with the exact error I'm getting:

![image](https://user-images.githubusercontent.com/10199417/36393200-f0b6ec9a-15ae-11e8-855f-57e728801312.png)

**Actual Behavior**:

The API above crashes with a `JsonSerializationException`. My best bet is that MEGA changed their JSON response for that API, so the library requires an update to reflect that in the mapped C# class.

**Steps to Reproduce**:

1. Just call `MegaApiClient.GetAccountInformationAsync` with a logged client

**MegaApiClient Version**:
Both the latest NuGet version and a previous one.

**Comment by Sergio0694** [comment]
**UPDATE:** it started working again (across all versions and builds), maybe we can assume it was just a temporary glitch with their server responses? 🤔

**Comment by gpailler** [comment]
As you said, maybe they pushed a wrong update of their API.

**Comment by Sergio0694** [comment]
@gpailler Yeah that's probably it, but I had opened the issue anyways just in case it was an intentional API change on their end to let you know as soon as possible. Glad that's not the case anyways 😄
