### ISSUE TITLE
Can't get all subnodes from a megalink

### ISSUE THREAD

**Issue by jangix** [gpailler/MegaApiClient#87]
**Description**
*Using 1.6.2.396 version,  when I call a getNodesFromLink(myPublicLink) method I get only the nodes which are located in a root folder insted of getting also all nodes included in the subfolders, which I should get by using getNodes().
Am I doing something wrong or is there any mistake?  How can I get all subnodes from a public link ? 
Thank You.*

**Comment by gpailler** [comment]
Thanks for the report. Seems you found a bug ;-)
I checked the code and I confirm only the first level is retrieved.

**Comment by gpailler** [comment]
Could you try the version of MegaApiClient and tell me if you have all your subnodes?
https://ci.appveyor.com/project/gpailler/megaapiclient/build/1.6.2.407/artifacts

**Comment by jangix** [comment]
*Thanks for the fix, using 1.6.2.407 version, now seems to get the children correctly too.
Please attention: getNodesFromLink (myPublicLink) don't produce any NodeType.Root element. The node of the root folder is of type NodeType.Directory!
Using getNodes(parent), the results do not contain the parent folder node as a NodeType.Root!
The NodeType.Root element must always be present after the call of these methods otherwise an inverse recursive mode would not be possible.*

**Comment by gpailler** [comment]
Thanks for the feedback and thanks for your comment about NodeType.Root. I will continue to work on it.

**Comment by jangix** [comment]
Also that thing should be checked:  client.getNodesFromLink(GetDownloadLink(parent))

**Comment by gpailler** [comment]
@jangix I applied your request about Root node and null parent.
Could you test the custom build to ensure the behavior is as expected and you don't face any issue?

You can install the package from MyGet: https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient/1.6.3-87-GetNode-411 or directly from AppVeyor: https://ci.appveyor.com/project/gpailler/megaapiclient/build/1.6.3.411/artifacts

Thanks

**Comment by gpailler** [comment]
1.6.3 released
