### ISSUE TITLE
Unicode is not supported

### ISSUE THREAD

**Issue by KAS1990** [gpailler/MegaApiClient#96]
**Description**:
Why library doesn't supports unicode passwords
*what are you trying to do*
I try to ligin with password "Пароль12345"

**Actual Behavior**:

*what happens*
Login failed

**Expected Behavior**:

*what should happen* 
Login to my account, besause this is right password

**Steps to Reproduce**:

1. Create password wich contains non-latin letters, for example, russain, german special letters
2. Try to login using MegaApiClient

**MegaApiClient Version** : 1.5.0

**Comment by KAS1990** [comment]
I try to change func ToBytes(this string data)
from return Encoding.UTF8.GetBytes(data);
to return Encoding.Unicode.GetBytes(data);
But nothing changed.

**Comment by KAS1990** [comment]
try use all other encodings: BigEndianUnicode, Default, ASCII. Result - error either BadArguments or ResourceNotExists. I need your help!!!

**Comment by gpailler** [comment]
I reproduce the issue. I will investigate

**Comment by gpailler** [comment]
@KAS1990 Could you check the following build of MegaApiClient and confirm the issue is fixed?
https://www.myget.org/feed/megaapiclient/package/nuget/MegaApiClient/1.6.3-96-unicode-420

**Comment by KAS1990** [comment]
I couldn't install this package by PM console, therefore i download sources and built library. But result is the same - error ResourceNotExists. I am interested in what changes did you make. There were supporting net4.6 and deletion unused method Extensions.CopyTo. I think it could't solve problem. I use net4.0.

**Comment by gpailler** [comment]
The bugfix is on the branch 96-unicodepassword, not on master.
You can see it here https://github.com/gpailler/MegaApiClient/compare/96-unicodepassword

I'm waiting your confirmation before merging to master ;-)

**Comment by KAS1990** [comment]
Great! It works. Can you download new version do nuget, to i can download and install package from PM console or VS Nuget Manager?

**Comment by gpailler** [comment]
I will prepare 1.6.3 release for today

**Comment by KAS1990** [comment]
Thank you. I am waiting it.

**Comment by gpailler** [comment]
1.6.3 released
