### ISSUE TITLE
File Name Encoding Problem

### ISSUE THREAD

**Issue by garsia0** [gpailler/MegaApiClient#99]
**Description**:

*what are you trying to do*

Sync Local Folder / MegaFolder

**Actual Behavior**:

CharacterEncoding Mitmatch
*what happens*

**Expected Behavior**:

*what should happen* 

i get list nodes and get node.name use this name for File.Exist(name) and return false
only happen on files no standar character set example ('        SσяэRυbϊσ♥.jpg)
and receive from api ( SσяэRυbϊσ♥.jpg)
what is encoding the api use for the names

**Steps to Reproduce**:

1.  get file list from folder
2. compare string local and remote name
3. 

**MegaApiClient Version**:
1.6.3.424

**Comment by gpailler** [comment]
Everything uses UTF-8 with Mega so the encoding of the characters should be correct.
In your example, the characters looks similar (except the quote and space).
Could you try to call `System.Text.Encoding.UTF8.GetBytes(variable)` on both variables to compare the results?
